### ISSUE TITLE
 Error: Unexpected error. Status Code: Forbidden Microsoft.Graph.ServiceException: Code: accessDenied

### ISSUE THREAD

**Issue by danielbrunt57** [lavinir/hassio-onedrive-backup#10]
I just installed this on Supervised HA 2022.11.2 on my HA "Blue" ODROID N2+.  I completed the authentication steps which were successful, restarted the add-on but the log shows this error:
```
11/10/2022 20:30:55 Info: Backup interval configured to every 72 hours
11/10/2022 20:30:57 Error: Unexpected error. Status Code: Forbidden
Microsoft.Graph.ServiceException: Code: accessDenied
11/10/2022 20:30:57 Info: Interval Completed.
Message: Access denied
Inner error:
	AdditionalData:
	date: 2022-11-10T20:30:57
	request-id: f5e4cfd0-8b49-4b33-bd66-804b26adc179
	client-request-id: f5e4cfd0-8b49-4b33-bd66-804b26adc179
ClientRequestId: f5e4cfd0-8b49-4b33-bd66-804b26adc179
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.DriveRequest.GetAsync(CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 155
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54
```

**Comment by lavinir** [comment]
That's odd. Reading the drive metadata was (for free space monitoring) was added in the last version. But I haven't encountered an instance where this was failing using the same permission scopes.
Were you running the previous version fine ?

**Comment by danielbrunt57** [comment]
This us my first running this...

**Comment by riemers** [comment]
`11/13/2022 09:49:50 Info: Backup interval configured to every 72 hours
11/13/2022 09:49:51 Error: Unexpected error. Status Code: Forbidden
Microsoft.Graph.ServiceException: Code: accessDenied
Message: Access denied
Inner error:
11/13/2022 09:49:51 Info: Interval Completed.
	AdditionalData:
	date: 2022-11-13T09:49:51
	request-id: ac38e745-6fef-4eca-aa05-e9625a800204
	client-request-id: ac38e745-6fef-4eca-aa05-e9625a800204
ClientRequestId: ac38e745-6fef-4eca-aa05-e9625a800204
   at Microsoft.Graph.HttpProvider.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Microsoft.Graph.BaseRequest.SendRequestAsync(Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.BaseRequest.SendAsync[T](Object serializableObject, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Microsoft.Graph.DriveRequest.GetAsync(CancellationToken cancellationToken)
   at hassio_onedrive_backup.Graph.GraphHelper.GetFreeSpaceInGB() in /src/Graph/GraphHelper.cs:line 155
   at hassio_onedrive_backup.Program.Main(String[] args) in /src/Program.cs:line 54`

Have the exact same issue, authenticated, came back got this error message. Fresh install.

**Comment by lavinir** [comment]
Don't have an explanation for why that specific permission would fail only for some people but I'll add a fix for this to silently fail when getting the available space in OneDrive without compromising the rest of the backup logic and it will just mean the added sensor won't be able to show the remaining available storage in OneDrive.

**Comment by riemers** [comment]
My account is an office (my own) o365 business account. So could be that it differs from personal accounts?
________________________________
Van: lavinir ***@***.***>
Verzonden: Sunday, November 13, 2022 2:28:16 PM
Aan: lavinir/hassio-onedrive-backup ***@***.***>
CC: Erik-jan Riemers ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lavinir/hassio-onedrive-backup] Error: Unexpected error. Status Code: Forbidden Microsoft.Graph.ServiceException: Code: accessDenied (Issue #10)


Don't have an explanation for why that specific permission would fail only for some people but I'll add a fix for this to silently fail when getting the available space in OneDrive without compromising the rest of the backup logic and it will just mean the added sensor won't be able to show the remaining available storage in OneDrive.

**Comment by danielbrunt57** [comment]
Mine also is my my own business account...

**Comment by danielbrunt57** [comment]
I have a personal account albeit with only 15 GB {or is it 5 GB?} which I can try. My business account has 1 TB...

**Comment by riemers** [comment]
Can’t hurt to try
________________________________
Van: Daniel ***@***.***>
Verzonden: Sunday, November 13, 2022 7:27:17 PM
Aan: lavinir/hassio-onedrive-backup ***@***.***>
CC: Erik-jan Riemers ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lavinir/hassio-onedrive-backup] Error: Unexpected error. Status Code: Forbidden Microsoft.Graph.ServiceException: Code: accessDenied (Issue #10)


I have a personal account albeit with only 15 GB {or is it 5 GB?} which I can try. My business account has 1 TB...

**Comment by danielbrunt57** [comment]
It works fine with my Microsoft OneDrive Basic 5GB account so the permissions issue is with Microsoft OneDrive for Business accounts.

**Comment by danielbrunt57** [comment]
This appears to be related info...
https://learn.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_get?view=odsp-graph-online

**Comment by lavinir** [comment]
Oh .. It's OneDrive for Business :( 

Yes that's exactly the relevant call. Only the permissions scope I'm using is not even listed there and is only available for Personal Accounts.  
OneDrive for business is not supported because of the inability to use that permission scope (see [relevant issue](https://github.com/lavinir/hassio-onedrive-backup/issues/5). ).

Sorry to say the only workaround until OneDrive for Business adopts the App Folder support would be for the add-on to have access to all your OneDrive files and that's a no go for me.

I'll add this explicitly to the README so it's clear.
