### ISSUE TITLE
How to set time for OneDrive Backup to start a backup?

### ISSUE THREAD

**Issue by ziptbm** [lavinir/hassio-onedrive-backup#100]
Is it possible to set the time of day that it starts a backup?/

**Comment by lavinir** [comment]
see [here](https://github.com/lavinir/hassio-onedrive-backup#allowed-hours-optional)

**Comment by ziptbm** [comment]
> see [here](https://github.com/lavinir/hassio-onedrive-backup#allowed-hours-optional)

Thank you. ahhh, I totally missed this I was looking for something in the web UI or something along the lines of "backup start time."  closing this out.  Thanks again.
