### ISSUE TITLE
File sync delete files in OneDrive

### ISSUE THREAD

**Issue by sliann** [lavinir/hassio-onedrive-backup#103]
I have the following configuration:

local_backup_num_to_keep: 10
onedrive_backup_num_to_keep: 30
backup_interval_days: 1
backup_name: hass_backup
monitor_all_local_backups: true
ignore_upgrade_backups: false
hass_api_timeout_minutes: 30
notify_on_error: true
exclude_media_folder: true
exclude_ssl_folder: false
exclude_share_folder: false
exclude_local_addons_folder: false
sync_paths:
  - /media/
file_sync_remove_deleted: true
excluded_addons: []
log_level: verbose

The upload of files with file sync is working as expected. However several files are deleted from OneDrive because they according to the log does not exist in the sync folder. This is not the case since the file is there.

Any help would be appreciated 😊

**Comment by lavinir** [comment]
Hard to say without looking at the logs.. :) Could you please adjust the log level to "Verbose" and share the relevant logs ?

**Comment by sliann** [comment]
Here are the log:

08/11/2023 09:23:58 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807152756.jpg
08/11/2023 09:23:58 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807152756.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:58 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807152756.jpg
08/11/2023 09:23:58 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153704.jpg
08/11/2023 09:23:58 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153704.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:58 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153704.jpg
08/11/2023 09:23:58 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153704.mp4
08/11/2023 09:23:58 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153704.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:58 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153704.mp4
08/11/2023 09:23:58 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153734.jpg
08/11/2023 09:23:58 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153734.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:58 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807153734.jpg
08/11/2023 09:23:59 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154348.mp4
08/11/2023 09:23:59 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154348.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:59 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154348.mp4
08/11/2023 09:23:59 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154349.jpg
08/11/2023 09:23:59 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154349.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:59 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154349.jpg
08/11/2023 09:23:59 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154904.jpg
08/11/2023 09:23:59 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154904.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:59 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154904.jpg
08/11/2023 09:23:59 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154904.mp4
08/11/2023 09:23:59 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154904.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:23:59 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807154904.mp4
08/11/2023 09:24:00 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807160336.jpg
08/11/2023 09:24:00 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807160336.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:00 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807160336.jpg
08/11/2023 09:24:00 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807160336.mp4
08/11/2023 09:24:00 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807160336.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:00 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807160336.mp4
08/11/2023 09:24:00 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161421.jpg
08/11/2023 09:24:00 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161421.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:00 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161421.jpg
08/11/2023 09:24:00 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161421.mp4
08/11/2023 09:24:00 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161421.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:00 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161421.mp4
08/11/2023 09:24:01 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161433.jpg
08/11/2023 09:24:01 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161433.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:01 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161433.jpg
08/11/2023 09:24:01 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161444.jpg
08/11/2023 09:24:01 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161444.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:01 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161444.jpg
08/11/2023 09:24:01 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161633.mp4
08/11/2023 09:24:01 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161633.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:01 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161633.mp4
08/11/2023 09:24:02 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161634.jpg
08/11/2023 09:24:02 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161634.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:02 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161634.jpg
08/11/2023 09:24:02 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161645.jpg
08/11/2023 09:24:02 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161645.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:02 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161645.jpg
08/11/2023 09:24:02 [33] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161749.jpg
08/11/2023 09:24:02 [33] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161749.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:02 [33] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161749.jpg
08/11/2023 09:24:02 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161749.mp4
08/11/2023 09:24:02 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161749.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:02 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807161749.mp4
08/11/2023 09:24:03 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162147.jpg
08/11/2023 09:24:03 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162147.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:03 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162147.jpg
08/11/2023 09:24:03 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162147.mp4
08/11/2023 09:24:03 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162147.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:03 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162147.mp4
08/11/2023 09:24:03 [29] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162543.jpg
08/11/2023 09:24:03 [29] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162543.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:03 [29] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162543.jpg
08/11/2023 09:24:04 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162543.mp4
08/11/2023 09:24:04 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162543.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:04 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807162543.mp4
08/11/2023 09:24:04 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163229.jpg
08/11/2023 09:24:04 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163229.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:04 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163229.jpg
08/11/2023 09:24:04 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163229.mp4
08/11/2023 09:24:04 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163229.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:04 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163229.mp4
08/11/2023 09:24:04 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163638.jpg
08/11/2023 09:24:04 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163638.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:04 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163638.jpg
08/11/2023 09:24:05 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163638.mp4
08/11/2023 09:24:05 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163638.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:05 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163638.mp4
08/11/2023 09:24:05 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163650.jpg
08/11/2023 09:24:05 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163650.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:05 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807163650.jpg
08/11/2023 09:24:05 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164241.jpg
08/11/2023 09:24:05 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164241.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:05 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164241.jpg
08/11/2023 09:24:06 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164241.mp4
08/11/2023 09:24:06 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164241.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:06 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164241.mp4
08/11/2023 09:24:06 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164317.jpg
08/11/2023 09:24:06 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164317.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:06 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164317.jpg
08/11/2023 09:24:06 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164321.mp4
08/11/2023 09:24:06 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164321.mp4 not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:06 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807164321.mp4
08/11/2023 09:24:06 [21] Verbose: Evaulating FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807165417.jpg
08/11/2023 09:24:06 [21] Info: /media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807165417.jpg not included in Sync Paths. Deleting from OneDrive
08/11/2023 09:24:06 [21] Info: Deleting item: FileSync/media/ringeklokke/ftp/2023/08/07/Inngangsdor_00_20230807165417.jpg

Here are a picture of the three first files deleted:
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/79062704/c2b52fe6-4014-482a-b8ff-8e6f4f2c4efc)

**Comment by lavinir** [comment]
Yes this is a bug. Will add a fix for this in the next version hopefully

**Comment by sliann** [comment]
Thank you for checking it😊 great job with the add on 👍🏻

**Comment by lavinir** [comment]
Should be solved in 2.2, now released.
