### ISSUE TITLE
Feature Request: Limit backup time window while allowing file sync to run as soon as a new file is store on the disk

### ISSUE THREAD

**Issue by marcgarciamarti** [lavinir/hassio-onedrive-backup#106]
Can I in someway restrict backups to only happen during a certain period of time of the day, and yet have the File Sync feature to immediately sync files throughout the day?

thanks!!

**Comment by lavinir** [comment]
You can now toggle an [option](https://github.com/lavinir/hassio-onedrive-backup#ignore-allowed-hours-for-file-sync) to ignore allowed hours for file syncing.
