### ISSUE TITLE
after updated to version 2.2 i get an error

### ISSUE THREAD

**Issue by ageurtse** [lavinir/hassio-onedrive-backup#113]
After updated to version 2.2 i get the error message below:

An error has occurred. This application may no longer respond until reloaded. 

After hitting reload, the message directly appear again, settings can't be saved. 
I'm running HA 
Home Assistant 2023.9.3 
Supervisor 2023.09.2 
Frontend 20230911.0 - latest 

I restarted HA, and the addon nothing seems to help, what could be wrong ?

**Comment by Edenglish92** [comment]
> Yes, previous version was running fine. Log file is without error's
> 
> because off the default settings, it is going to backup imideatly that isn't fine. I have a prety large media folder because off camera recordings wish shouldn't be uploaded.
> 
> Please alter that also.

Same issue after applying update. Addon was working fine before. After the update, the UI is broken without any error on the log.

**Comment by ageurtse** [comment]
after uninstalling and reinstalling it looks like it is working.

**Comment by lavinir** [comment]
Thanks @ageurtse. Just to make sure, for those that haven't done so please try a hard refresh see if that helps

**Comment by lavinir** [comment]
@Edenglish92, I have a vague recollection when I started testing the addon a while back that I had this issue and if memory serves, a hard refresh fixed it - might be an easier fix the re installing the addon

**Comment by Edenglish92** [comment]
> @Edenglish92, I have a vague recollection when I started testing the addon a while back that I had this issue and if memory serves, a hard refresh fixed it - might be an easier fix the re installing the addon

What is a "hard refresh" please ? So I can test

**Comment by lavinir** [comment]
> > @Edenglish92, I have a vague recollection when I started testing the addon a while back that I had this issue and if memory serves, a hard refresh fixed it - might be an easier fix the re installing the addon
> 
> What is a "hard refresh" please? So I can test 

Hard refresh of the page in your browser, usually Ctrl+F5

**Comment by Edenglish92** [comment]
It works after a second installation... I did not change anything so I cannot explain why.
My history: 
- 2.1.2 upgrade to 2.2 with UI Broken (nothing on log)
- revert to backup 2.1.2: working OK
- re-installation 2.2: working OK

**Comment by Edenglish92** [comment]
> It works after a second installation... I did not change anything so I cannot explain why. My history:
> 
> * 2.1.2 upgrade to 2.2 with broken UI (nothing on log)
> * revert to backup 2.1.2: working OK
> * re-installation 2.2: working OK
> 
> PS: the configuration did not go well (migration of the config on HA to config on the addon). I had to reconfigure everything.

@lavinir issue still present on mobile App... the UI is broken on my mobile HA App (show in sidebar integration) but it works on my PC or using a browser on my mobile.

**Comment by jymorel** [comment]
after installation, require to clear the browser cache and reconfigure everything.  And also clear the application cache of the mobile app...

**Comment by Doughboy68** [comment]
Same got error. I just uninstalled, re-installed and reconfigured.

**Comment by Edenglish92** [comment]
> after installation, require to clear the browser cache and reconfigure everything. And also clear the application cache of the mobile app...

Thanks! I confirm it did solve my issue on the mobile app.
