### ISSUE TITLE
Error when changing Backup interval (days) to 0.5, but it will save the change! 

### ISSUE THREAD

**Issue by vinnie1234** [lavinir/hassio-onedrive-backup#114]
When I change "Backup interval (days)" to 0.5 for every 12 hours, it got an error that the value must be greater than 1. But is will save the change!

![image](https://github.com/lavinir/hassio-onedrive-backup/assets/10955777/af821457-814e-4fb9-b97d-52d7a3f6b2df)

**Comment by Doughboy68** [comment]
I noticed the same.

**Comment by lavinir** [comment]
Hi, so it doesn't really persist the change (it will not survivor a restart of the addon). This is indeed a bug, will add a fix for this.

**Comment by vinnie1234** [comment]
Aah, didn't test it indeed to restart the Addon. Tnx!

**Comment by lavinir** [comment]
fixed in 2.2
