### ISSUE TITLE
After update 2.2 new backups show up as partial

### ISSUE THREAD

**Issue by JIK12345** [lavinir/hassio-onedrive-backup#115]
When I trigger a backup from the dashboard it now shows up as a partial backup instead of a full backup (below image right). When I trigger a backup from HA/System/Backups it does create a full backup (below image left)

I don't see a setting that could be causing this. No folders are excluded.

<img width="635" alt="Screenshot 2023-10-03 122610" src="https://github.com/lavinir/hassio-onedrive-backup/assets/113934344/22bd5046-4f80-46f1-bcd0-b8e005974760">

**Comment by lavinir** [comment]
Thanks, added a bug.

**Comment by lavinir** [comment]
fixed in 2.2
