### ISSUE TITLE
v2.2 User interface does not open anymore

### ISSUE THREAD

**Issue by chrissyshw** [lavinir/hassio-onedrive-backup#116]
After updating to version v2.2 the user interface does not open anymore. The Logs of the Add-On are here - seems fine to me:

 [1] Info: No new settings file. Attempting to restore from legacy configuration
10/03/2023 11:18:40 [1] Info: Anonymous Telemetry Disabled
10/03/2023 11:18:40 [1] Info: Backup interval configured to every 24 hours
10/03/2023 15:09:38 [50] Info: Creating new backup
10/03/2023 15:09:38 [50] Info: Starting full local backup
10/03/2023 15:11:37 [52] Info: Backup complete
10/03/2023 15:11:37 [54] Info: Found 1 backups to upload.
10/03/2023 15:11:37 [54] Info: Uploading hass_backup_2023-10-03-15-09 (10/03/2023 15:09:38)
10/03/2023 15:11:37 [54] Info: Fetching Local Backup (Slug:bbb90b67)
10/03/2023 15:11:40 [52] Info: Backup (bbb90b67) fetched successfully
10/03/2023 15:11:40 [52] Info: Starting file upload. (Size:235448320 bytes. Attempt: 1/3)
10/03/2023 15:13:00 [53] Info: Upload completed successfully

**Comment by lavinir** [comment]
Please see #113 . A hard refresh (clear cache) is required after upgrading to the new version. Let me know if you still have issues after that.

**Comment by chrissyshw** [comment]
Thanks for the quick reply. I have now cleared the cache, restarted HA, as well as used different browsers, however the problem still occurs.

I now get a 502: Bad Gateway Error and still the error message that the add-on could not be started.

I also noticed that I no longer have any settings options under "Options". (See Screenshot)

![2023-10-03 22_00_18-Home Assistant – Mozilla Firefox](https://github.com/lavinir/hassio-onedrive-backup/assets/85548135/d19a98b7-6bb4-43e0-8daf-28b0e4c6ca08)

**Comment by lavinir** [comment]
Ok Bad Gateway is a different problem.  Options have moved to the addon itself so it makes sense you don't see any there.  
So what exactly is happening - If the addon isn't starting how are you getting logs ?

Could you try uninstalling and re-installing the add on just to make sure we have a clean start ?

**Comment by chrissyshw** [comment]
After a re-installation the problem is fixed. I guess there was something broke in my configuration. Thank you for your help!
