### ISSUE TITLE
Progress meter shows negative numbers V2.2.2

### ISSUE THREAD

**Issue by andyp05** [lavinir/hassio-onedrive-backup#120]
I triggered a back up and saw this during the upload and after the upload was finished. 

![image](https://github.com/lavinir/hassio-onedrive-backup/assets/14006401/91d3f4b3-e124-4ece-acc0-c72eecf0681e)

**Comment by lavinir** [comment]
it showed a negative number during upload and the progress bar remained that way after upload was complete ?

**Comment by andyp05** [comment]
The progress bar would go from blank to negative numbers every couple of seconds during upload. It also continued for a minute or two after it looked like everything was completed. The dashboard said synced or backed up after it said 'syncing'

**Comment by lavinir** [comment]
Did it happen for a specific file or do you see an issue with the number for all uploads ?do you have the logs from the upload ?

**Comment by andyp05** [comment]
I just looked at the logs and they don't go back far enough to when I saw the error. The Frigate addon uploads dozens of files at a time from the media folder.  This is the latest log file with some errors in it. Not sure if directly related to this issue.
[de91e161_hassio_onedrive_backup_2023-10-04T19-42-07.175Z.log](https://github.com/lavinir/hassio-onedrive-backup/files/12807547/de91e161_hassio_onedrive_backup_2023-10-04T19-42-07.175Z.log)

**Comment by andyp05** [comment]
1. Triggered a backup
2. Clicked upload
3. Upload went to 100%
4. 4 seconds later the progress bar flashed negative number.
5. Progress bar went blank.

Logs:
10/04/2023 15:45:15 [40] Info: Creating new backup
10/04/2023 15:45:15 [40] Info: Starting partial local backup
10/04/2023 15:46:33 [39] Info: Backup complete
10/04/2023 15:47:30 [10] Info: Uploading hass_backup_2023-10-04-15-45 (10/04/2023 15:45:15)
10/04/2023 15:47:30 [10] Info: Fetching Local Backup (Slug:dbd7414f)
10/04/2023 15:47:30 [39] Info: Backup (dbd7414f) fetched successfully
10/04/2023 15:47:31 [10] Info: Starting file upload. (Size:146667520 bytes. Attempt: 1/3)
10/04/2023 15:47:52 [38] Info: Upload completed successfully
10/04/2023 15:47:59 [39] Info: File /media/frigate/frigate.db-wal out of sync. Starting Upload
10/04/2023 15:47:59 [39] Info: Starting file upload. (Size:4177712 bytes. Attempt: 1/3)
10/04/2023 15:48:02 [38] Info: Upload completed successfully
10/04/2023 15:48:02 [38] Info: File /media/frigate/frigate.db-shm out of sync. Starting Upload
10/04/2023 15:48:02 [38] Info: Starting file upload. (Size:32768 bytes. Attempt: 1/3)
10/04/2023 15:48:04 [38] Info: Upload completed successfully

**Comment by lavinir** [comment]
I see an a timeout issue uploading one of the files. That shouldn't happen, maybe it's related to the progress being reported for that file. If you are able to set the log level to verbose and share another batch of file uploads if it includes an error that would be helpful.
