### ISSUE TITLE
 Remove deleted files during File Sync issue

### ISSUE THREAD

**Issue by andyp05** [lavinir/hassio-onedrive-backup#121]
V 2.2.2

The old backups are being deleted in Onedrive however, the FileSync files are not. 

Is this expected behavior or a bug?

Thanks

**Comment by lavinir** [comment]
Could you give some more details ? What do you mean old backups are getting deleted ? If backups are being removed that shouldn't please share the logs

**Comment by andyp05** [comment]
The actual 'backups' are being removed from OneDrive when the newer backups are created, and the older ones are removed. I only keep 10 in OneDrive, so when the 11th is created, the oldest is deleted in HA and OneDrive as expected. 

I Filesync the media separately. Older files are removed from HA's media folder after 10 days (I am using Frigate with a 10 day retention). However, those files are not removed from OneDrive.
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/14006401/f12875fc-bdff-410d-819b-a883ab96bcfe)

**Comment by lavinir** [comment]
Ok so the issue is with files not being removed not backups.
If the file is deleted and you have that toggle to remove deleted files then it should also be removed from OneDrive. 
Please set log level to 'Verbose' and share the logs for a File Sync interval - It will begin with the message : "Evaulating File Sync Diffs"

**Comment by andyp05** [comment]
Did a full uninstall and reinstall. After an hour or so, I checked and the files gone from HA are now gone from OneDrive. 
Don't know if this will pop up again, but for now I will close issue.
Thanks
