### ISSUE TITLE
The settings tab in the WebUI is showing incorrect information

### ISSUE THREAD

**Issue by garyjohnwalker** [lavinir/hassio-onedrive-backup#124]
I've noticed this on 2.2.2 but it may exist on earlier instances.

In settings on the WebUI, the "Allowed Hours" field is populated with my microsoft username and "Backup Password" is populated with something (can't tell what as it's correctly showing dots to hide the contents).

The WebUI doesn't indicate that backups are being password protected and clearly my username can't limit the allowed hours so it looks like this is just a display issue.

**Comment by lavinir** [comment]
Thanks I'll check this.

**Comment by lavinir** [comment]
@garyjohnwalker , reading this again. Your microsoft username is not known / saved by the addon. There was a validation bug on the input fields of the settings page, I believe more likely you may have pasted that value in the 'allowed hours' field. 
I'm working on fixing the validation / display issues for the next version. If you notice any incorrect values actually being used please let me know.

**Comment by garyjohnwalker** [comment]
Hi lavinir,

I've just upgraded and both the above fields are now correctly blank on the settings tab. No adverse affects as far as I can tell.

Thanks for the quick fix!

Gary
