### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by labanex** [lavinir/hassio-onedrive-backup#126]
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/45422071/606cfcea-1bee-4ee0-b68f-1a143202f395)
I am not able to set to Verbose. It swings to Info on Save.
Also, it would be nice to see very descriptive data and information on what these settings do in the app description. Is Verbose Everything?
Thanks.

**Comment by labanex** [comment]
local_backup_num_to_keep: 25
onedrive_backup_num_to_keep: 25
backup_interval_days: 1
backup_name: hass_backup
monitor_all_local_backups: true
ignore_upgrade_backups: false
hass_api_timeout_minutes: 30
notify_on_error: true
exclude_media_folder: false
exclude_ssl_folder: false
exclude_share_folder: false
exclude_local_addons_folder: false
sync_paths: []
file_sync_remove_deleted: false
excluded_addons: []
log_level: verbose

Is says verbose here in the YAML file. So maybe it is set, but not showing in Log Level GUI.

Thanks!

**Comment by lavinir** [comment]
Actually the yaml config is deprecated. I will follow up on the display of the log verbosity and open a bug if needed. 
Not sure what other explanation is needed for the logs it's pretty standard log level selection.

Did you have a specific reason to change to verbose? Any issues running the addon?

**Comment by lavinir** [comment]
Should be fixed in 2.2.3
