### ISSUE TITLE
"Not logged in!" error - "That code didn't work. Check the code and try again."

### ISSUE THREAD

**Issue by gefriedman** [lavinir/hassio-onedrive-backup#127]
As per instructions, I navigated to https://microsoft.com/devicelogin and entered the code at the top of the screen.
It gave an error message, "That code didn't work. Check the code and try again."

OneDrive is running ok on that PC that is running HASSIO as a virtual machine now, it was disconnected for a while due to a password change.

OneDrive Backup 2.2.2
Home Assistant 2023.10.0
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231002.0 - latest

Can you please assist? I am concerned that backups are not running.

Thanks

Gary

**Comment by lavinir** [comment]
If you see a message that you need to log in, backups aren't running (you can verify in the logs)
The password change probably invalidated the token. Usually a restart of the addon solves this. You should get a new code to use after restart

**Comment by gefriedman** [comment]
As you suggested, I restarted the addon, got a new code, and it worked!  THANKS!

p.s. I may respectfully suggest you add a line about restarting the addon if necessary to the dialog box that talks about signing in with https://microsoft.com/devicelogin.

**Comment by lavinir** [comment]
I will add something in the Readme for toubleshooting.
