### ISSUE TITLE
Syncing about every 6 minutes the last backup

### ISSUE THREAD

**Issue by troelde** [lavinir/hassio-onedrive-backup#130]
After upgrade to latest version 2.2 file syncing backup last night starts about every 5 minutes. See log below. Same behavior on two different HA instances:

Home Assistant 2023.10.0
Supervisor 2023.10.0
Operating System 10.5

What is wrong?

10/08/2023 04:32:48 [22] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 04:32:48 [22] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 04:33:47 [22] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 04:33:48 [78] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 04:41:46 [21] Info: Upload completed successfully
10/08/2023 04:47:52 [17] Info: Found 1 backups to upload.
10/08/2023 04:47:52 [17] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 04:47:52 [17] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 04:48:18 [33] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 04:48:19 [33] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 04:56:32 [20] Info: Upload completed successfully
10/08/2023 05:02:56 [61] Info: Found 1 backups to upload.
10/08/2023 05:02:56 [61] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 05:02:56 [61] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 05:03:30 [52] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 05:03:31 [52] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 05:11:39 [61] Info: Upload completed successfully
10/08/2023 05:18:00 [30] Info: Found 1 backups to upload.
10/08/2023 05:18:00 [30] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 05:18:00 [30] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 05:18:36 [23] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 05:18:37 [23] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 05:26:40 [33] Info: Upload completed successfully
10/08/2023 05:33:05 [18] Info: Found 1 backups to upload.
10/08/2023 05:33:05 [18] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 05:33:05 [18] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 05:33:39 [7] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 05:33:40 [7] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 05:41:48 [78] Info: Upload completed successfully
10/08/2023 05:48:09 [14] Info: Found 1 backups to upload.
10/08/2023 05:48:09 [47] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 05:48:09 [47] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 05:48:52 [17] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 05:49:03 [17] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 05:57:02 [20] Info: Upload completed successfully
10/08/2023 06:03:12 [25] Info: Found 1 backups to upload.
10/08/2023 06:03:12 [25] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 06:03:12 [25] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 06:03:36 [28] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 06:03:37 [28] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 06:11:43 [18] Info: Upload completed successfully
10/08/2023 06:18:16 [36] Info: Found 1 backups to upload.
10/08/2023 06:18:16 [36] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 06:18:16 [36] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 06:19:02 [36] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 06:19:02 [61] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 06:27:04 [61] Info: Upload completed successfully
10/08/2023 06:33:19 [33] Info: Found 1 backups to upload.
10/08/2023 06:33:19 [14] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 06:33:19 [14] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 06:33:57 [14] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 06:33:57 [14] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 06:42:01 [33] Info: Upload completed successfully
10/08/2023 06:48:23 [15] Info: Found 1 backups to upload.
10/08/2023 06:48:23 [73] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 06:48:23 [73] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 06:49:03 [15] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 06:49:04 [15] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 06:57:22 [52] Info: Upload completed successfully
10/08/2023 07:08:27 [21] Info: Found 1 backups to upload.
10/08/2023 07:08:27 [21] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 07:08:27 [21] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 07:08:54 [22] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 07:08:54 [26] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 07:17:05 [29] Info: Upload completed successfully
10/08/2023 07:23:32 [60] Info: Found 1 backups to upload.
10/08/2023 07:23:32 [60] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 07:23:32 [60] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 07:23:58 [37] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 07:23:59 [37] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 07:32:10 [32] Info: Upload completed successfully
10/08/2023 07:38:35 [75] Info: Found 1 backups to upload.
10/08/2023 07:38:35 [53] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 07:38:35 [53] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 07:39:02 [47] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 07:39:02 [47] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 07:47:02 [47] Info: Upload completed successfully
10/08/2023 07:53:39 [30] Info: Found 1 backups to upload.
10/08/2023 07:53:39 [30] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 07:53:39 [30] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 07:54:17 [30] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 07:54:18 [30] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 08:02:20 [47] Info: Upload completed successfully
10/08/2023 08:08:44 [40] Info: Found 1 backups to upload.
10/08/2023 08:08:44 [40] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 08:08:44 [40] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 08:09:13 [31] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 08:09:13 [31] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 08:17:15 [76] Info: Upload completed successfully
10/08/2023 08:23:48 [53] Info: Found 1 backups to upload.
10/08/2023 08:23:48 [40] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 08:23:48 [40] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 08:24:13 [40] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 08:24:13 [39] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)
10/08/2023 08:32:18 [17] Info: Upload completed successfully
10/08/2023 08:38:57 [61] Info: Found 1 backups to upload.
10/08/2023 08:38:57 [61] Info: Uploading hass_backup_2023-10-07-00-45 (10/07/2023 00:45:05)
10/08/2023 08:38:57 [61] Info: Fetching Local Backup (Slug:dd50ef8d)
10/08/2023 08:39:37 [61] Info: Backup (dd50ef8d) fetched successfully
10/08/2023 08:39:38 [61] Info: Starting file upload. (Size:351703040 bytes. Attempt: 1/3)

**Comment by lavinir** [comment]
The addon 'wakes up' every 5 minutes to check if it needs to do anything. this is not new to 2.2 but the issue I'm seeing in your logs, seems that it is uploading the same backup each time meaning it isn't recognizing that the upload is already uploaded to OneDrive (I assume you see it in OneDrive). Possibly something corrupt in its metadata and if you remove it from OneDrive it could resolve this. 

However if you want to help me debug this, appreciate if you could go to OneDrive and share the additional "info" available on the backup file in OneDrive.

**Comment by troelde** [comment]
Thanks for quick response. The problem was solved after adding unique i[nstance names](https://github.com/lavinir/hassio-onedrive-backup#backup-instance-name-optional). Seems that this config was not converted during upgrade to 2.2, ref. "_All configuration options have been moved from Home Assistant to the addon itself. The addon will attempt to migrate the old settings but if this fails, settings will be reverted to defaults! Make sure you go over all settings after upgrading._".

**Comment by lavinir** [comment]
Yes the migration of the old settings didn't seem to go over as well as I'd hoped unfortunately. Glad you got it working.
