### ISSUE TITLE
Enable the use of secrets in the password configuration setting

### ISSUE THREAD

**Issue by marcgarciamarti** [lavinir/hassio-onedrive-backup#132]
Hi,

I've checked the documentation and I don't see a reference to using HA secrets file for retrieving the encryption password. Unless this is already possible, could you consider this feature request for future evolutions of the add-on?

thanks a lot for such an awesome add-on!!

**Comment by lavinir** [comment]
Currently there is no support for this. But I'm curious, since this is stored inside the addon, what is the benefit of having it read from the secrets file ? It's not exposed in the configuration yaml file.

**Comment by marcgarciamarti** [comment]
I must say I can't compare how secure the current approach is versus having the secret file in the secrets.yaml. I asked for this solely because have been a Google Backup user for a long time, and that add-on uses the secrets.yaml file.

**Comment by lavinir** [comment]
I don't think either is really more secure. Both store the password in clear text. The addon stores it inside it's own container. the Secrets.yaml exists on the host itself also passwords in clear text.
