### ISSUE TITLE
Filesync not getting triggered

### ISSUE THREAD

**Issue by marcgarciamarti** [lavinir/hassio-onedrive-backup#136]
Hello,

I wonder what I'm doing wrong. Files are being created in the folder that the add-on is watching for new files, yet file sync is not getting triggered.

Could it be the case that the add-on won't monitor a folder that is excluded from backups? if not, how should I go about troubleshooting this?

<img width="535" alt="Screenshot 2023-10-14 at 17 05 29" src="https://github.com/lavinir/hassio-onedrive-backup/assets/12695572/46fcfb3a-0ea0-477c-8b89-bb74d7197e40">

Cheers on such a wonderful add-on!

**Comment by lavinir** [comment]
You should add a '/' at the end of the folder name so it's /media/frigate/

Also, note that unless you set the toggle to ignore allowed hours for file sync, it will only take place during the allowed hours set. 
If you are still having issues please make sure to attach your logs

**Comment by lavinir** [comment]
@marcgarciamarti - was this resolved for you ?

**Comment by marcgarciamarti** [comment]
> @marcgarciamarti - was this resolved for you ?

I think so. I wanted to confirm a couple of things before posting an update like the time it takes to replicate the information once it's on disk, but it certainly looks very good as the data is actually propagated to OneDrive.

I love this add-on!

**Comment by lavinir** [comment]
great glad to hear it.
