### ISSUE TITLE
Repeated warnings in Supervisor log about missing options in OneDrive Backup schema

### ISSUE THREAD

**Issue by mikeynp** [lavinir/hassio-onedrive-backup#138]
In v2.2.3 (and probably ongoing since the v2.2 update as I've only just noticed it in v2.2.3) I'm getting repeated blocks of warnings in the Supervisor log about missing options in the OneDrive Backup schema, as follows:

```
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'local_backup_num_to_keep' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'onedrive_backup_num_to_keep' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'backup_interval_days' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'backup_name' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'monitor_all_local_backups' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'hass_api_timeout_minutes' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'notify_on_error' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'exclude_media_folder' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'exclude_ssl_folder' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'exclude_share_folder' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'exclude_local_addons_folder' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'sync_paths' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'file_sync_remove_deleted' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'excluded_addons' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'log_level' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
23-10-20 16:56:42 WARNING (MainThread) [supervisor.addons.options] Option 'backup_allowed_hours' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)
```

Presumably these are because the options in question have now moved to the GUI in the OneDrive Backup addon itself, but are repeated many times over. The backups are still working just fine, so this is annoying rather than an actual problem. Is there anything I can change/edit to prevent them occurring, short of reinstalling the add-on? Thanks.

**Comment by lavinir** [comment]
Yes technically you usually go to the addon config and choose to edit the raw config but I looked now and it seems that option is not available when there is no config at all for  the addon (as is t he case now that I moved everything). 
I guess that's stored somewhere on the machine but not sure exactly where. 
'
One option is to find that file and remove those entries.
The other would be to uninstall and reinstall the addon which should clear the old settings.

Sorry for the inconvenience.

**Comment by shypike** [comment]
You can get rid of the warnings, but it can be destructive.
Make sure you have SSH access, with "protection" off and open a session.
Use "docker ps" to find the ID of the OneDrive Backup container (the first 5 chars are enough), e.g. 5c342.
Run "docker exec -it 5c342 /bin/sh".
Replace the file "/data/settings.json" with a file that contains just "{}", so just those two braces without the quotes.
Type "exit" to leave the container and another "exit" to leave the SSH session.
Then restart the OneDrive Backup add-on.
WARNING: The add-on will reset all of your options to defaults and that may lead to removed backups both local and on OneDrive.
So this will get rid of the warnings, but will also remove existing backups beyond the default 10!

**Comment by shypike** [comment]
Forget my previous advice.
Another restart of the add-on will result in new warnings, because the settings.json file will be restored to its original (with default values). So the warnings will also return.
So my suspicion is that the add-on is doing something wrong after all.

**Comment by lavinir** [comment]
The supervisor warnings should not be related to the settings.json. That file is created by the addon itself and the Supervisor is not aware of it or its contents so I don't believe that will remove the warnings but it **will** certainly reset the settings.

The warnings come from previous entries to native Home Assistant addon configuration that I am no longer using. They get would get mapped to an "options.json" file inside the data folder but I'm not sure removing that if it exists would be enough (it might be stored by Home Assistant somewhere else as well).

**Comment by shypike** [comment]
Yes, you are correct. Sorry for the confusion.
However, the /data/options.json file is empty (well, it just has the two braces).
The way the supervisor deals with add-ons is very poorly documented, so I can imagine that it's not easy for you to solve.
Also, the source of the mapping of /data (/mnt/data) is not accessible from the SSH session.

**Comment by shypike** [comment]
I filed a bug report for the Supervisor and I got this very useful answer:

> You can address these problems. Go to [Settings -> Addons -> OneDrive Backup](https://my.home-assistant.io/redirect/supervisor_addon/?addon=de91e161_hassio_onedrive_backup&repository_url=https%3A%2F%2Fgithub.com%2Flavinir%2Fhassio-onedrive-backup). Then go to the configuration tab. Switch to YAML mode at the top and remove any deprecated options.

>The add-on dev can also fix this for you as well. For example, notice the [reset_database option in the Nginx Proxy Manager community addon](https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/v0.11.0/proxy-manager/DOCS.md#option-reset_database). The way this option works is when a user sets it to true it resets the internal DB to a blank slate. The add-on itself then removes this option from its own config for the user to prevent them from accidentally resetting their database every time it restarts. You can see how it does that here:
https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/f5c53c130c6a29b8b1d5a06b80cc1c8261705b65/proxy-manager/rootfs/etc/cont-init.d/mysql.sh#L31-L32

>Supervisor could remove the option since it sees that its no longer in the schema. I think the reason we don't is because then that information would be lost. If config had changed or moved somewhere else users may wish to see the previous value to know what they used to have when setting the new one. It's something to consider. In the meantime though this can be fixed by both users and add-on devs currently.

**Comment by mikeynp** [comment]
> You can address these problems. Go to [Settings -> Addons -> OneDrive Backup](https://my.home-assistant.io/redirect/supervisor_addon/?addon=de91e161_hassio_onedrive_backup&repository_url=https%3A%2F%2Fgithub.com%2Flavinir%2Fhassio-onedrive-backup). Then go to the configuration tab. Switch to YAML mode at the top and remove any deprecated options.

@shypike This looks like it worked! I followed the instructions above, deleted all the options in YAML mode, saved the configuration, then restarted the add-on as requested. The config was replaced with a message that said "This add-on has no configuration" and I've not seen the warning message since. Many thanks!

**Comment by lavinir** [comment]
Oh cool. @shypike - thanks for following up. I guess there were legacy settings you had the YAML option. I thought it was hidden for you. In my setup it's gone because there is no config but I guess it didn't remove yours. 

Just didn't understand their reference on how I can solve this at the addon level - The example the was sent was for clearing state in a DB but the point is to clear the addon config saved by Home Assistant. Anyway glad there is a solution that works 👍

**Comment by shypike** [comment]
Sorry cannot help you solve this issue, because I also have no clue what the referenced code does.  
Very few people will see the Supervisor log and now there's a work-around.  
Good enough, I'd say.  
Compliments for your great add-on.

**Comment by shypike** [comment]
The documentation for add-ons was extended in reaction to my reported issue:

>::note If you remove a configuration option from an add-on already deployed to users, it is recommended to delete the option to avoid a warning like Option '<options_key>' does not exist in the schema for <Add-on Name> (<add-on slug>).

>To remove an option the Supervisor addons API can be used. Using bashio this boils down to bashio::addon.option '<options_key>' (without additional argument to delete this option key). Typically this should be called inside an if block checking if the option is still set using bashio::config.exists '<options_key>'. ::

Full document: https://github.com/home-assistant/developers.home-assistant/blob/master/docs/add-ons/configuration.md
