### ISSUE TITLE
Dark mode background stops being dark when scrolling down the page

### ISSUE THREAD

**Issue by mikeynp** [lavinir/hassio-onedrive-backup#139]
When running with dark mode enabled, the background stops being dark about half way down the page when scrolling through the backups in dashboard view. Even with the dark background, there also seem to be white borders on each side. Reproducible in Safari v17 and Edge v116.

![1](https://github.com/lavinir/hassio-onedrive-backup/assets/112195228/e2c7b691-bc15-4021-baaa-6406b9e80a27)

**Comment by lavinir** [comment]
Fixed in 2.2.4
