### ISSUE TITLE
Backup password not working

### ISSUE THREAD

**Issue by SuperPino64** [lavinir/hassio-onedrive-backup#144]
I've set a password in the WEB-UI under settings -> Backup password.
However all (newly) created backups aren't password protected. 

I'm on the latest version 2.2.3 and I've restarted the add-on, HA and complete server multiple times.

When I download the backup.tar file from my onedrive I can extract it without the need of a password.
What could be wrong?

**Comment by lavinir** [comment]
Assuming your settings are correct. Make sure you're testing this correctly. 
The main TAR file of the backup itself is not password protected. Inside you have multiple tar.gz files for the different backup components. They are the ones protected. Did you try and extract those ?

**Comment by lavinir** [comment]
This is just the way Home assistant handles encrypted backups. The addon is not creating them in a special way.

See : https://github.com/sabeechen/decrypt-ha-backup

Should help you extract the tar manually
