### ISSUE TITLE
File Sync and Full Backup problems 

### ISSUE THREAD

**Issue by Al-Dek** [lavinir/hassio-onedrive-backup#148]
**1. File Sync works partially.**
File Sync Paths settings: 
/config/*yaml , 
/ssl/, 
/addons/.
File sync works only on /ssl/ path.
Verbose log:
.......
11/15/2023 08:35:22 [38] Verbose: Found 0 local backups that can be removed (Generational Rules)
11/15/2023 08:40:22 [62] Verbose: Evaulating File Sync Diffs
11/15/2023 08:40:22 [62] Verbose: Evaluating file: /ssl/fullchain.pem
11/15/2023 08:40:22 [62] Verbose: File: /ssl/fullchain.pem up to date. No sync required
11/15/2023 08:40:22 [62] Verbose: Evaluating file: /ssl/privkey.pem
11/15/2023 08:40:22 [53] Verbose: Checking backups
11/15/2023 08:40:22 [53] Verbose: Backup Interval Completed.
11/15/2023 08:40:22 [53] Verbose: File: /ssl/privkey.pem up to date. No sync required
11/15/2023 08:40:22 [53] Verbose: Retrieving existing local backups...
11/15/2023 08:40:22 [53] Verbose: Retrieving existing online backups...
.....
There are no attempts (during last 24 h) to synchronize other paths... (

**2. Missing Full Backup**
Backup settings:
     Number of local backups: 10
     Number of OneDrive backups: 15
     Backup interval (days): 1
     Generational backups - Days: 7
     Generational backups - Weeks: 4
     Generational backups - Months: GenMonths (Optional)
     Generational backups - Years: GenYears (Optional)
     Backup name: hass_backup
     Backup instance name: Enter backup instance name (Optional)
     Allowed hours: 7-9

Initially, full backup scheduled on period 2-4 is missing without any errors or warnings in the log.
To check, I reassigned the backup window to 7-9 hours.
The result is the same - there is no full backup, verbose log has no errors...

**Comment by lavinir** [comment]
1. I was unable to reproduce this. Make sure settings are saved properly. If it's still not working for you, try to take one of the paths that are not syncing and just using that as a single path just for testing and see what happens. Also you don't need to wait for the allowed hours to debug, just toggle on the ignore allowed hours for file sync.
2. Hard to say anything about this without logs. Each cycle the addon will tell you in the logs if it needs to backup or why it's skipping a backup. Feel free to share those logs.

**Comment by Al-Dek** [comment]
1. Removed all folders from File Sync Paths 
2. Removed folder /FileSync/ , subfolder /ssl  and files inside from OneDrive.
3. Set Allowed Hours to 14-16.
4. Set path for File Sync as /config/*.yaml
5. Have saved all settings.
6. Restarted HA
Log file after restart is attached.
File Sync folders were successfully replicated to OneDrive (except 2 yaml files with 0 size and empty /addons/ folder)
Full backup, assigned on 14-16, still missed. 
For today there is only one partial backup (addon_core_samba_11.0.0  dated11/15/2023 07:33:37).
Screenshots of Setting are attached

[de91e161_hassio_onedrive_backup_2023-11-15.log](https://github.com/lavinir/hassio-onedrive-backup/files/13366011/de91e161_hassio_onedrive_backup_2023-11-15.log)
![OneDrive-Backup-1](https://github.com/lavinir/hassio-onedrive-backup/assets/98658555/1bc34c63-3de2-4873-9a65-4aad36990f7c)
![OneDrive-Backup-2](https://github.com/lavinir/hassio-onedrive-backup/assets/98658555/aae3644e-07ea-4e6d-808f-4930b8a4ae7b)
![OneDrive-Backup-3](https://github.com/lavinir/hassio-onedrive-backup/assets/98658555/5a721ea0-5348-4f94-aaf6-fa13d48891d5)

**Comment by Al-Dek** [comment]
Hi!
I found out why the daily backup was not performed - it is performed only after at least 24 hours from the moment of any last backup, including partial backups. This may be the reason for skipping several daily full backups if there were partial system updates during these days...

**Comment by Al-Dek** [comment]
Got it.
Thanx.
