### ISSUE TITLE
Full backups missing something

### ISSUE THREAD

**Issue by akostamo** [lavinir/hassio-onedrive-backup#151]
Hi, 

And thanks for this fantastic add-on! You already saved me quite lots of hours being a new HASS user. <3 

But I think there is something missing from the backup: I needed to restore from full backup yesterday because I was messing around with my raspberry and cut my sd card in half (lol.. noob). 

I had pretty nicely working setup made and did the restore from the previous day and I had to fully install zigbee2mqtt (edge) and reconfigure it, mosquitto broker and the MQTT integration. 

That was not so bad, but still the full backup seems to be somewhat selective, or what do you think? Is there something that is intentionally left behind from the backups? 

My settings looks like this (i think these are the default ones): 
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/100792730/b6c88212-f2dd-4c1d-ad2b-f7e8b15e2520)
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/100792730/7445fbdf-0b79-42cd-8cd0-0c47f7ad4c2f)

**Comment by rorypjm** [comment]
I've seen similar with more .... described in a separate issue in #151.
If you have been seeing what I have in 151, then they may be related.

**Comment by lavinir** [comment]
@akostamo ,
If you haven't chosen to ignore any addons, everything should be backed up including Z2M, Mosquito etc. The addon is using Hass's built in API to perform the backups. 
You can take a look at the backup after it's created and check that everything you expect is there (either by opening the archive or just choosing 'restore' in HASS and it will show you everything backed up).

If you see something missing still, please add the backup logs (set to verbose).

**Comment by lavinir** [comment]
@akostamo - Still have an issue ?
