### ISSUE TITLE
Infinit upload

### ISSUE THREAD

**Issue by Schnix84** [lavinir/hassio-onedrive-backup#153]
Hi, 

First I want to say thank you for this addon. It served me well for quite some time but now I had to deactivate it for a reason. 

I recently discovered that the addon is constantly trying to upload the last backup file when the OneDrive storage is almost full and so cant store any more backup files to it. 

As a result I had gigabytes of outgoing traffic per hour. 

Maybe you can have a look into it. 

Kind regards

**Comment by lavinir** [comment]
Yeah that seems like a reasonable optimization to add..

**Comment by lavinir** [comment]
fixed in 2.3
