### ISSUE TITLE
Backups folder accessed every 5 minutes

### ISSUE THREAD

**Issue by PodgyMonkey** [lavinir/hassio-onedrive-backup#156]
Hi,

Thanks for the great add-on

In the Supervisor log I am seeing the add-on access the /backups folder multiple times every 5 minutes:

23-12-29 04:37:09 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:37:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:37:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:42:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:42:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:42:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:47:10 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:47:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:47:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:52:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:52:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:52:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:57:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:57:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 04:57:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 05:02:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 05:02:11 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup
23-12-29 05:02:12 INFO (MainThread) [supervisor.api.middleware.security] /backups access from de91e161_hassio_onedrive_backup

My backups are only scheduled once per day

Is this normal behaviour?

**Comment by lavinir** [comment]
Yes so the addon wakes up every 5 minutes to see if it has any work to do. To determine this, it is querying the existing backups from Home assistant.
