### ISSUE TITLE
Feature requests: Statistics summary and next planned backup

### ISSUE THREAD

**Issue by kedar-1** [lavinir/hassio-onedrive-backup#160]
Hello,

thanks for a great add-on.

It will be helpfull to see more statistics about backups (as was in Google backup Addon).

For example - summary page:
Local backups (7,8 GBs ) 
Onedrive backups (3,5 GBs)
Last Backup Date:
Next Backup Data:

Thanks

**Comment by lavinir** [comment]
Yes seems reasonable. Last Backup Date already exists in the overview now :)

**Comment by lavinir** [comment]
Available now in 2.3
