### ISSUE TITLE
Problem  HA 2024.1.0 (2024.1.1, 2024.1.2)

### ISSUE THREAD

**Issue by mc2343** [lavinir/hassio-onedrive-backup#161]
)

![fail](https://github.com/lavinir/hassio-onedrive-backup/assets/79168518/8a3be433-f65a-4235-a828-47ace1fde7ab)

After I have updated HA to version 2024.1.0, (same 2024.1.1, 2024.1.2).

**Comment by lavinir** [comment]
That's not a lot to go on.
Where do you see this is related to this Addon ? That error is referencing a 'backup' integration. This does not look like an 'addon' error and while it says 'backup' it is not the name of this addon ..

**Comment by mc2343** [comment]
Problem solved, Sorry my mistake.
