### ISSUE TITLE
Local Backups are not listed in OneDrive

### ISSUE THREAD

**Issue by NCO3** [lavinir/hassio-onedrive-backup#162]
Hi there,
first of all I would like to thank you for this great tool to backup HA on a remote location!

I have set my system to save one local and 5 OD backups.
The internal HA backup function is disabled.

When I check the backups after a while, I recognize, that the UI shows 0 local backups and 5 remote backups although I see two `backup.tar` which are in `/backup`.
If I compare the file size, these two backups match to 2 remote backups on OD.
Because of space constraints I need to delete the rar files manually every now and then, but after a while the same mismatch happens again:
Backups are created, sometimes are shown as local (and they are physically in /backups), but one day, they are not listed in the UI as local, but obviously synched to OD, but still in the backup folder.

I have activated "monitor all local backups" since quite a while.

**Comment by lavinir** [comment]
Not sure I got all the details but backup.tar is a weird artifact. If "monitor all local backups" is enabled and you believe there is a mismatch in what the addon is showing you, please make sure this is aligned with what you see in Home Assistant under Settings -> System -> Backups.  Are any backups listed there ?

**Comment by NCO3** [comment]
Sorry for the delay, @lavinir 
With backup.tar I meant all backup tars (e.g. 033485ff.tar created by OneDrive)
I currently have a mismatch again:
This yellow one is in backup:
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/15801364/2a8454bb-bcb0-4747-a7bc-ce912143e1e9)
But is not shown here::
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/15801364/bd2bc02e-f900-48b8-a7f9-229fe0b23dda)
In the OneDriveBackup View there is 0 local backups listed.
Every now and then I need to delete the local one due to space constraints, but the last time is about two weeks ago.
Any idea why OneDriveBackup is out of sync?
(under system > backup there are no backups listed)
Thank you.

**Comment by lavinir** [comment]
If you have 1 configured local back up. It should keep the last one, however if you deleted that backup it will not be downloaded from OneDrive. Next local backup created will be kept. You can follow what's happening in the logs.

The addon is also querying Home Assistant to get the local backups and not assuming anything or trying to access the file system so if you aren't seeing any Home Assistant backups under System -> Backup it means Home Assistant does not see any local backups and neither will the Addon. 

If you are not manually deleting any addons and still do not see one local backup retained after creation please send the logs.
