### ISSUE TITLE
Generational Backups not working - only deleting the oldest daily backup

### ISSUE THREAD

**Issue by ChavezD** [lavinir/hassio-onedrive-backup#165]
I noticed that my settings regarding generational backups are not applied and instead only one daily backup is kept. Eventually the oldest one of those local&OneDrive backups will be deleted, with the following settings beeing ignored:

I'm not 100% if I got the idea of the settings correctly, but here are my settings and what I believe they would mean. Please correct me if I'm wrong:

- Number of local/OneDrive backups: 35 - no matter of the following settings, there are never more than 35 backups stored. (I would be willing to increase this number, if I notice the schedule is working and I'm not having enough buffer)
- Backup interval (days): 1 - each day a backup is created
- Generational backups - Days: 7 - the daily backup is kept for one week
- Generational backups - Weeks: 4 - each week one of the daily backups is kept for ~1 month
- Generational backups - Months 12 - each month one of the beforementioned backups is kept for one year.
- Generational backups - Years - 5 - For each year there would be one backup from avove that will not be deleted for 5 years

So my educated guess would be, that every day a backup is created and it's deletion takes place according to the pattern set in the generational backups settings. Now instead, the oldest backup (No. 35), is deleted and I have 35 consecutive daily backups, instead of e.g. 4 weekly and one monthly backup (with maybe additional daily backups to top up to 35). 

Maybe I'm completely on the wrong path and someone could explain me how to properly adjust the settings to keep backups for longer than 35 days. 
Have a nice sunday everyone! :)

**Comment by lavinir** [comment]
So no this is not correct. 
Generation Days - 4 would mean that you want to have a backup for each of the last 4 days.
Generational Weeks 2 - Would mean you want to have a backup for this week and a backup from the previous week.
Generational Month - 12  - Would mean you want one backup from each of the last 12 months - A backup for January, February,  March etc.

**Comment by ChavezD** [comment]
Thanks for the fast reply, but how should I set it up then if I wand to keep "some" old backups - so that it's not only daily like right now?
I don't particularry need a super big/old history, but a small amount would be nice to have just in case.

**Comment by lavinir** [comment]
usually you would take a few days back in the daily generations so let's say you have 3 backups from the last 3 days.
If you add 2 weekly backups it means you'll always have one from the current week and one from the previous week.
If you add 6 monthly backups you would keep a backup for each of the last 6 months.

**Comment by Jordan87** [comment]
Should we count generation backups into "Number of OneDrive backups"
i.e. if I have configured 12 "Generational backups - Months" but "Number of OneDrive backups" is configured only to 10 will it remove oldest monthly backups?
