### ISSUE TITLE
Upgrade Issues to 2.3 Thread

### ISSUE THREAD

**Issue by lavinir** [lavinir/hassio-onedrive-backup#173]
Hi all,

I've noticed some upgrade issues there are similar caching issues as with the [2.2 upgrade](https://github.com/lavinir/hassio-onedrive-backup/issues/113)

UI library was updated and seems this requires clearing the browser cache. If that does not solve your issue a reinstall of the addon should do the trick.

Sorry for the inconvenience.

**Comment by lavinir** [comment]
That's actually a good idea. I Will add this in a future version to save the settings in OneDrive so that they can be fetched on re install

**Comment by pgale** [comment]
After the update, I'm not connecting to onedrive. It's just showing as initialising. It reconnected with the code ok (eventually). Is this related or something else?

**Comment by Stephan-4711** [comment]
Store the backup settings locally would be nice I wouldn't like to upload the password for the backups to the cloud storage

**Comment by lavinir** [comment]
If the addon is removed where would the local copy be stored ? 
It's a valid point about the password but it's probably still useful to backup the settings to the cloud omitting the password, which can be entered again post settings restore.
