### ISSUE TITLE
Getting error logs in HA Supervisor related to this add0on 

### ISSUE THREAD

**Issue by invisible999** [lavinir/hassio-onedrive-backup#177]
I am getting following entries regularly in HAOS Superviour log:

24-02-11 18:03:36 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository

24-02-11 18:03:38 WARNING (SyncWorker_6) [supervisor.addons.validate] Add-on config using incompatible map options, 'addon_config' and 'homeassistant_config' are ignored if 'config' is included. Please report this to the maintainer of OneDrive Backup

24-02-11 18:03:38 WARNING (SyncWorker_0) [supervisor.addons.validate] Add-on config using incompatible map options, 'addon_config' and 'homeassistant_config' are ignored if 'config' is included. Please report this to the maintainer of OneDrive Backup

Also got following log entry as well
`The recorder backlog queue reached the maximum size of 68258 events; usually, the system is CPU bound, I/O bound, or the database is corrupt due to a disk problem; The recorder will stop recording events to avoid running out of memory
`
After some searching there are messages that scheduled backup causes such problem.

**Comment by lavinir** [comment]
Regarding the folder mapping warnings, I will open a bug and fix in the next minor release.

For the Recorder issue - That is relevant to the amount of state changes for entities. I'm not sure what you mean that you identified this is related to the addon - but if you see an excessive amount of updates to the OneDrive backup sensor entity please share the relevant info.
