### ISSUE TITLE
Can't authenticate any more

### ISSUE THREAD

**Issue by Jurgen-DOUCHY** [lavinir/hassio-onedrive-backup#181]
My authentication was broken suddenly.
And reauthenticating does not seem to work
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/120566296/43869724-479d-4d75-ade9-363d4098a082)

**Comment by bosremco** [comment]
I have the same issue

**Comment by bogdantodireanu** [comment]
Same here

**Comment by Andyve1461** [comment]
Same here

**Comment by tane64** [comment]
After restarting HA and the addon authentication works again.
