### ISSUE TITLE
backup file not removed in HA after upload to onedrive and new backupt created

### ISSUE THREAD

**Issue by eddysteurs** [lavinir/hassio-onedrive-backup#186]
since a few days i notice my diskusage going up every time a backup has ran.
After investigation is seems addon is not removong older backups from HA (after sync to ondedrive and new backup is created)
Addon only mentions  or zero (although minimum local is 1) but several files remain in the HA backup folder. In HA system backups nothing is mentioned.

![image](https://github.com/lavinir/hassio-onedrive-backup/assets/9960284/22f943f1-e3d7-4f68-bb57-cf084f8ae24d)
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/9960284/1e5f6d1e-ac18-44fa-a0b8-5b4a73ba6e90)
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/9960284/9d671156-7a89-458e-8537-5e3bed0e0e0b)

Have restarted addon, HA, remove and reinstall addon already but problem remains
HA is 2024.2.6  Ondedrive addon 2.3

**Comment by mrkaqz** [comment]
I have the same issue. I have to SSH to remove the file from /backup folder manually.
Noticed the back up file did not show in HA backup file list in Settings > System > Backup when reload the UI showing this error in the supervisor logs.

24-02-28 18:46:17 ERROR (MainThread) [supervisor.backups.backup] Can't read backup tarfile /data/backup/28b27c7e.tar: "filename './backup.json' not found"

**Comment by eddysteurs** [comment]
no they do not appear in system - backups, only in the folder backups, so they don't get deleted, it has been taken by the developper of the supervisor (seems related to size) and should be solved in supervisor 2024.2.1
