### ISSUE TITLE
No longr working

### ISSUE THREAD

**Issue by Vladx71** [lavinir/hassio-onedrive-backup#187]
This addon since the last update is no longer working. I can successfully authenticate at Microsoft, but it seems addon does not recognise this and stuck in initialise phase

v2.3

**Comment by lavinir** [comment]
There were some instances of this reported in another issue. My guess is it's related to some caching conflicting with the new authentication libraries. 
This was usually resolved after one of these actions:
1. Restart Addon
2. Restart Home Assistant
3. Uninstall and re-install the addon.

**Comment by palmfieldsflame** [comment]
> There were some instances of this reported in another issue. My guess is it's related to some caching conflicting with the new authentication libraries. This was usually resolved after one of these actions:
> 
>     1. Restart Addon
> 
>     2. Restart Home Assistant
> 
>     3. Uninstall and re-install the addon.

No Luck. it is still stuck Initializing.

**Comment by Vladx71** [comment]
I decided to move to google drive integration until it is fixed

L:

**Comment by wilksy** [comment]
same issue here. restarting etc did nothing. abandoning for another solution.

**Comment by robaston9** [comment]
Opening the sign in link in an incognito window and signing in worked for me. There seems to be an issue with the authentication if your browser is already signed into Microsoft services and causes the sign in to get "stuck" when the add on opens the sign in page.

**Comment by clowgg** [comment]
@lavinir - How do you recreate the 'sign in for the first time' situation if you're stuck in this 'initialising' state?

**Comment by clowgg** [comment]
I went ahead and uninstalled / reinstalled / used a InPrivate browser window to do the auth. Worked.

**Comment by lavinir** [comment]
Hi @clowgg - Yes currently there is no way to force clear the authentication record if the addon thinks it was established, that is without uninstalling. 
Glad it worked.
