### ISSUE TITLE
I new code to sign to OneDrive

### ISSUE THREAD

**Issue by Palo47** [lavinir/hassio-onedrive-backup#190]
Provided code for expired. The expiration was announced at the last step and there is no error anywhere else.
Please provide a new code or what to do and me go update re-generated.
Thank you

**Comment by JNyquist-telia** [comment]
+1
Same thing happens to me when I try to authenticate with the provided code.

**Comment by lavinir** [comment]
Restarting the addon should generate a new code

**Comment by JNyquist-telia** [comment]
That actually worked this time, but also by opening the Microsoft authentication link in a private Chrome window.
I tried a bunch of times yesterday, even rebooting the whole HASS server, but today it finally worked!

Cheers,

/Jonas
