### ISSUE TITLE
Our services aren't available right now

### ISSUE THREAD

**Issue by sys1aeg** [lavinir/hassio-onedrive-backup#191]
after the upgrade had to re authenticate - now getting 
Our services aren't available right now

We're working to restore all services as soon as possible. Please check back soon.

**Comment by lavinir** [comment]
Sounds like a transient error. Was this resolved ? If not please share more details on where you are receiving this error exactly / any relevant logs.

**Comment by sys1aeg** [comment]
You are correct it was transient Sent from my jitterbug On Mar 16, 2024, at 5:14 PM, lavinir ***@***.***> wrote:﻿
Sounds like a transient error. Was this resolved ? If not please share more details on where you are receiving this error exactly / any relevant logs.
