### ISSUE TITLE
Addons and backups disappeared after install

### ISSUE THREAD

**Issue by ciclocaffe** [lavinir/hassio-onedrive-backup#194]
Hi, something very strange is happening. I had the google drive backup addon installed. I wanted to switch to this one. I installed this Onedrive backup addon. I did run the backup once (I did set it up so to keep track of every newly created backup) and what's happening is that all my addons are gone (but apparently working). The Settings > Addons is empty. The left menu is missing the addons. The Settings > System > Backups is empty. The supervisor log is not loading.

The Core log errors are the following:

```
Logger: homeassistant.components.hassio
Source: components/hassio/__init__.py:560
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 19 March 2024 at 23:48:59 (51 occurrences)
Last logged: 11:13:12

Can't read Supervisor data:
```

```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 00:16:59 (13 occurrences)
Last logged: 11:14:10

Failed to to call /host/info -
Failed to to call /backups -
Failed to to call /addons -
```

```
Logger: homeassistant.components.hassio
Source: helpers/update_coordinator.py:350
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 01:20:09 (5 occurrences)
Last logged: 11:05:50

Error fetching hassio data: Error on Supervisor API:
```

```
Logger: homeassistant.components.hassio.handler
Source: components/hassio/handler.py:602
integration: Home Assistant Supervisor (documentation, issues)
First occurred: 19 March 2024 at 23:48:37 (677 occurrences)
Last logged: 11:14:10

Timeout on /core/info request
Timeout on /host/info request
Timeout on /store request
Timeout on /addons request
Timeout on /backups request
```

The Supervisor Log doesn't load and it's stuck on to "Loading full log"

I have no idea how to debug this issue or revert. Any idea? thanks

Screenshots attached of what I see in the Addons and Backups page. Also in the left sidebar I used to have links to the addons (terminal, gdrive backup, onedrive backup etc)
![addons](https://github.com/lavinir/hassio-onedrive-backup/assets/105983464/81d08a5a-bde4-41a8-befc-0383778d3404)
![backups](https://github.com/lavinir/hassio-onedrive-backup/assets/105983464/ee642b1b-529a-4aad-a7d8-48aa0697beb4)

**Comment by lavinir** [comment]
That's indeed but this seems like a Home Assistant issue. The addon is just another docker container running, not sure how it can make this kind of impact on your installation.
You can try to ssh into your instance and list / remove addons via the CLI to see what's going on.

**Comment by ciclocaffe** [comment]
thanks. I managed to login through Putty. However where do I find a list of the commands I need to remove addons? thanks

**Comment by lavinir** [comment]
ha addons uninstall [slug]
