### ISSUE TITLE
Onedrive stuck "initializing"

### ISSUE THREAD

**Issue by jterfehr2000** [lavinir/hassio-onedrive-backup#199]
I have restarted the add-on and HA several times, Onedrive continues to fail to initialize.  Suggestions?
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/139287750/f5788b71-69cc-4a76-aa91-0958968a147b)

**Comment by lavinir** [comment]
Have you authenticated with OneDrive? 
Logs ?

**Comment by jterfehr2000** [comment]
I am sorry I am a relative newbie and not a programmer at all.  Yes, I authenticated with OneDrive and it had been previously working fine for months.  It is not giving me the option to re-authenticate.  I am sorry I don't know where to find any logs for this.  When I go to the logbook the only option is 'onedrive backup update' and there is nothing in the log.

**Comment by jterfehr2000** [comment]
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/139287750/f0bc2c06-385f-4766-a51f-3b9feaf49615)

**Comment by jterfehr2000** [comment]
There are no errors related to 'onedrive backup' in the logs.  (yes this troubleshooting helped me learn where "the logs" are and what is there)

**Comment by lavinir** [comment]
I hope you were looking at the addon specific logs. Could you please restart the addon and share those logs here ?

**Comment by jterfehr2000** [comment]
[1] Info: No new settings file. Attempting to restore from legacy configuration
04/15/2024 01:49:15 [4] Info: Anonymous Telemetry Disabled
04/15/2024 01:49:15 [4] Info: Backup interval configured to every 24 hours
04/15/2024 01:49:15 [4] Warning: Token cache is empty

**Comment by jterfehr2000** [comment]
The logs later provided a new code for one drive.  I put it in and it's all working again.  Thanks.
