### ISSUE TITLE
Missing optional configuration Toggle

### ISSUE THREAD

**Issue by merylen** [lavinir/hassio-onedrive-backup#200]
Used Version: 2.3.1
Installed on HAOS 12.1, Core: 2024.3.3

Under Settings -> Add-On -> OneDrive Backup -> Configuration is no toggle present to enable the optional functions. see screenshot. 
Is this intended? How can i enable the optional functions without this toggle.

![Bildschirmfoto 2024-04-09 um 09 20 43](https://github.com/lavinir/hassio-onedrive-backup/assets/2648705/0b4bb72a-438a-41e0-b157-b722c947c9aa)

Backup ist working fine. Just the toggle is missing.

**Comment by lavinir** [comment]
It's not missing, it was all moved inside the addon UI. 
see [Configuration](https://github.com/lavinir/hassio-onedrive-backup?tab=readme-ov-file#configuration)

**Comment by merylen** [comment]
I swear I looked 2 times. Both times I didn’t find it. 
Now I’ve found it. 
Thanks a lot!
