### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by Somel1978** [lavinir/hassio-onedrive-backup#204]
Hi

After signing in an confirm the code, It never logins and Microsoft page only displays:
![image](https://github.com/lavinir/hassio-onedrive-backup/assets/35574432/3bab6225-378e-405a-9db2-fdcfb8f0dc1a)

**Comment by lavinir** [comment]
That auth screen looks related to PassKeys. Does your account have those enabled? 
What do the logs show ?

**Comment by Somel1978** [comment]
Nothing stays waiting

**Comment by netforceatg** [comment]
Same here. I reinstalled it, and signed it in with the code on my iphone. And this time it worked

**Comment by manur37** [comment]
To solve it, I done the connection to microsoft account in private navigation.
