### ISSUE TITLE
Struggles With Authentication

### ISSUE THREAD

**Issue by sol3uk** [lavinir/hassio-onedrive-backup#207]
Hi,
I recently discovered your addon and am loving the idea.
However I just had to struggle past the authentication steps and I'm not sure if it's just me or if it's modern browsers in general (or ad blockers etc) but for me, Brave wasn't working, with or without adblockers. Edge wasn't working (no extensions or blockers installed).
I kept getting "Something went wrong, code has expired" errors, as well as a weird one on edge that just said "Fido View" after the Microsoft sign in step (and it's an MS browser, strange I know)! 

Finally, Firefox worked, but still took a couple of attempts and some restarts to refresh the auth token. 
It might be worth adding these troubleshooting steps or browser recommendations to the install documentation, as more basic users might struggle.

Happy to pop together a PR if I get the time!

**Comment by lavinir** [comment]
Yeah except for 'code expired', which is pretty self explanatory I think there are a bunch of different factors / settings that impact this but it is a standard Microsoft device auth flow. I think the "Fido" thing is something new that was introduced. Happy to add something to the troubleshooting section but I haven't seen anything consistent and different methods work / don't work for some people. 
I guess the most useful place if you're having issues for now is here in the issues.

**Comment by neil1111** [comment]
I had trouble with the code. So I uninstalled the add-on, and then re-installed and started it. That generated a new code, which worked for me. Hopefully this helps others.

**Comment by ZiroNL** [comment]
I also have problems with the authentication. I've logged in in Microsoft and verified the app, but it looks like the addon does not verify the authentication. When I restart the addon, a new code is given and the previous steps repeats.
I have tried many browsers, but the all do not work, Is it possible to get a button or so to activate the verification of the app after we've done the Microsoft steps?

**Comment by freggel2** [comment]
Same issue here. Installed the add-on. Followed the instructions. Authorized the add-on. But it keeps saying NOT LOGGED IN .

When I restart the application i'm given a new code. And the whole process starts all over again. It keeps saying not logged in.

Raspberry pi4,

**Comment by kevindt** [comment]
Similar issue here.  Using Edge browser.  Copy button next to the code does not copy the code.  Manually copied the code and authorized the add-on with Microsoft.  Verified that it is authorized on OneDrive.  Still won't show it is authorized in the add-on.  Restarting the add-in just generates a new code (which doesn't copy) - manually copied it. That one shows on Microsoft as expired!

**Comment by rstoica** [comment]
Same here - Chromium-based browsers (Edge, Chrome, Brave failed for me too), Firefox worked however. Did not really have the time to debug the root causes of such behavior though, but I suspect it may be related to how different user-agents handle FIDO authentication.

**Comment by raouldw** [comment]
I have the exact same issue. I authorized the app twice succesfully, but the add-on still says "Not logged in".

**Comment by freggel2** [comment]
> Same issue here. Installed the add-on. Followed the instructions. Authorized the add-on. But it keeps saying NOT LOGGED IN .
> 
> When I restart the application i'm given a new code. And the whole process starts all over again. It keeps saying not logged in.
> 
> Raspberry pi4,

My solution is to switch to another browser. The one I used is firefox and the authorization failed everytime. I switched to edge and put in the authorization code, connected and it worked.

**Comment by Thommelbommel** [comment]
For me it worked like this:
Restart the add-on to get a new code. Use Chrome-based Browser and go through the steps rather quick. That time I got no message code expired and it worked.

**Comment by caiocaminoski** [comment]
similar to @raouldw it worked in my 3rd attempt. First I tried in Chrome, then in Edge, then, finally, I open a private instance of edge (and this time it worked). Maybe it could be also related to how quick I got it authenticated the last time as mentioned by @Thommelbommel
