### ISSUE TITLE
Add on keeps crashing

### ISSUE THREAD

**Issue by Codiwr** [lavinir/hassio-onedrive-backup#208]
Been working well for past 5 months or so.

Latest version 2.3.1

On latest HA (Rpi) 12.2 Supervisor 4.4. Core 5.2.

After starting the add-on whether manually or from boot - When I go to check after an hour or so it's not running. Running the watchdog slows down HA and repeatedly causes it to crash/restart.

Any suggestions to identify the culprit, or is anyone else experiencing similar?

Shame, as I love the fact that a backup just happens overnight without having to think.about it.

Solution would be very much appreciated!

**Comment by lavinir** [comment]
Hard to say without any additional information. If it's crashing do you have any logs (both from the addon and supervisor) ?
