### ISSUE TITLE
Error finding timezone

### ISSUE THREAD

**Issue by tieskuh** [lavinir/hassio-onedrive-backup#21]
I get this error on startup. The integration works anyway but time is off 1 hour.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/115901851/205282231-76246ed6-5654-4944-80df-9acaff6ee782.png">

The file does exist:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/115901851/205282423-689feed2-346f-44e7-9cfa-d79477b3d52e.png">

Probably a permission issue

**Comment by lavinir** [comment]
I assume you're looking at the host file system, it's looking inside the container. 
I went back through my build logs and saw an issue with the armv7 image related to the required timezone package. 
Is this the architecture you are running on (hopefully :)) ?

**Comment by tieskuh** [comment]
No, I'm not running it in an container. I am running it on a Raspberry Pi. 

Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend-versie: 20221108.0 - latest

**Comment by tieskuh** [comment]
I see you already released an update in the mean time. I can confirm the issue is now gone. Thank you!
