### ISSUE TITLE
High CPU useage

### ISSUE THREAD

**Issue by JCalvi** [lavinir/hassio-onedrive-backup#210]
Looking for something else but noticed that dotnet onedrive-backup.dll fluctuates from 0.7 to 1.3% continuously on my RPi5 (htop).

No change whether I disable/enable the following:
  Either Telemetry
  File Sync
  Watchdog
  Hours enabled.
  Side Menu
  Logging Level

Really should not use any CPU when idle and not actively doing anything.

**Comment by lavinir** [comment]
There is also a web server that's always running to service the addon UI. I can't say if this is the reason for what you're seeing but other than the server for the UI, the only other business logic  running periodically is a check once a minute on the backup / file sync status - if nothing needs to be done it quits the cycle. 
I don't know if part of that infra is causing this or if this is something specific on your system although I'm not sure I'd say this is "High" CPU usage.
What do you see in Home Assistant in the Addon main page? On my machine it is showing 0 CPU usage when idle.

**Comment by JCalvi** [comment]
Add on page right now is showing 0.3% cpu use. 
Maybe yours is zero if you are using a machine much faster than a pi5?

**Comment by lavinir** [comment]
Yes that's a reasonable assumption. But since the addon is always doing "something" as a web server is running, it will never be complete zero. Maybe that's the diff with your cpu.

**Comment by JCalvi** [comment]
That could be the reason, would you consider an option to be able to stop the web server?

I generally don’t need to look at the interface and could start/stop it when I need to. I know it’s a small amount of cpu usage, but I try hard to keep my server running the minimum required cpu cycles and I only need the backup running when it runs once each day.

**Comment by JCalvi** [comment]
I think I found the culprit. 
https://community.home-assistant.io/t/folders-repeating-themself-in-core-when-accessing-via-samba/587573
My media folder was infinitely recursing and OneDrive backup was syncing it forever deeper.
I have removed the share and link and cpu seems to be back to zero.
