### ISSUE TITLE
Unable to Reinstall Home Assistant OneDrive Backup Add-on - “layer does not exist” Error

### ISSUE THREAD

**Issue by cibetik** [lavinir/hassio-onedrive-backup#211]
Hi,
thank you for this fantastic add-on!

**Description**:
I’m using the Home Assistant OneDrive Backup add-on, which was working well for backing up. Recently, I had to reinstall HAOS and restore it from a full backup created by this add-on. While the restore went smoothly, the add-on did not start, and I was unable to get it running again. I decided to uninstall it and attempt a fresh installation. However, I am now unable to reinstall the add-on due to the following error:

**Error Log:**
```
2024-05-20 19:13:00.272 INFO (MainThread) [supervisor.host.apparmor] Adding/updating AppArmor profile: de91e161_hassio_onedrive_backup
2024-05-20 19:13:00.384 INFO (MainThread) [supervisor.docker.interface] Downloading docker image ghcr.io/lavinir/aarch64-hassonedrive with tag 2.3.1.
2024-05-20 19:13:01.360 ERROR (MainThread) [supervisor.docker.interface] Can't install ghcr.io/lavinir/aarch64-hassonedrive:2.3.1: 500 Server Error for http+docker://localhost/v1.44/images/ghcr.io/lavinir/aarch64-hassonedrive:2.3.1/json: Internal Server Error ("layer does not exist")

```

**Steps to Reproduce**:

	1.	Reinstall HAOS.
	2.	Restore from a full backup created by the OneDrive Backup add-on.
	3.	Attempt to start the add-on (fails to start).
	4.	Uninstall the add-on.
	5.	Try to reinstall the add-on (installation fails with the above error).

**Expected Behavior**:
The add-on should start successfully after the restore and allow for reinstallation if uninstalled.

**Actual Behavior**:
The add-on fails to start post-restore and cannot be reinstalled due to a “layer does not exist” error.

**System Information**:

	•	Home Assistant OS: 12.3
	•	Supervisor: 2024.05.1
	•	OneDrive Backup Add-on: Version 2.3.1
	•	Hardware: RPi 3

**Additional Context**:
I have attempted several troubleshooting steps, including restarting the system and running` ha su repair`, but the issue persists.

Any guidance or assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by lavinir** [comment]
I doubt there's actually a problem pulling the image but you can try manually to make sure (from another device):
```
docker pull ghcr.io/lavinir/aarch64-hassonedrive:2.3.1
```
Assuming that works, try to run it on the PI. If it fails and you're on the same network I would think it's probably some caching / corruption in the local daemon. (Possibly a side effect of the restore?)

You can try pruning all unused objects though I'm not sure if this may have other effects for other addons if they are stopped. Proceed here with caution but I would start looking at the docker cache on the PI.

**Comment by cibetik** [comment]
I installed new HA and restored it from backup again in worked now.
