### ISSUE TITLE
Authenticate code does not work

### ISSUE THREAD

**Issue by charlesvandortmond** [lavinir/hassio-onedrive-backup#212]
Hi,

I had hassio-onedrive-backup installed and it created the 10 backups as set in the config. At some stage the creation of backups stopped and I got the message:

![image](https://github.com/lavinir/hassio-onedrive-backup/assets/74618517/34f4e55c-0e61-44fe-85e0-52d6358b88aa)

When following the instructions I got message:

![image](https://github.com/lavinir/hassio-onedrive-backup/assets/74618517/e3ecec69-90d9-4b50-941c-9eba774b3fc4)

I'm able to access my OneDrive manually and see the earlier created hassio backups. I have reinstalled hassio-onedrive-backup but the same issue is there still.

Any advise is welcome

Regards
Charles

**Comment by xXAtoMisEXx** [comment]
I have the same issue, the code does not work.

**Comment by Moqume** [comment]
I encountered the same, but the fix was easy: restart the add-on. That will generate a new code. I suppose that the code displayed has already expired by the time you see it.

**Comment by lavinir** [comment]
Yes that is correct. If the code expired a restart will give you a new one.
I am curious to understand though what happened for @charlesvandortmond as the authentication should not "expire" at some point. Did you uninstall the addon at some stage here or restore from backup ?

**Comment by charlesvandortmond** [comment]
@lavinir I have gone through the process again. This time I got all the correct screens from Microsoft, but in the end I was notified by Microsoft that the code had expired.... so I did the whole thing again, but now faster and then it worked....

**Comment by Moqume** [comment]
> Yes that is correct. If the code expired a restart will give you a new one.
> I am curious to understand though what happened for @charlesvandortmond as the authentication should not "expire" at some point. Did you uninstall the addon at some stage here or restore from backup ?

For me it was after an OS update and reboot. I noticed after a few days that my dashboard metrics didn't show the state of the backups and space available on One Drive. 

Going to the add-on, it showed the link and code, but Microsoft did not accept the code. 

This is when I restarted the add-on, the newly generated code worked fine.

Perhaps you can add a refresh button next to the code, for cases like this.

**Comment by lavinir** [comment]
Yes I will add it to the backlog
