### ISSUE TITLE
OneDrive Business support

### ISSUE THREAD

**Issue by ravdberg** [lavinir/hassio-onedrive-backup#216]
Hello,

I was wondering when OneDrive Business will be supported?
I have an account on that and do not want to buy the Personal one because of some legacy things.
Is their a particular reason this is not yet supported?
Is their a way I could help or are it limitations by Microsoft?

**Comment by lavinir** [comment]
See #5 
Until this API is supported by Microsoft it won't be in the addon unfortunately.
