### ISSUE TITLE
Wrong backup retained for yearly policy

### ISSUE THREAD

**Issue by lloyda** [lavinir/hassio-onedrive-backup#217]
Currently, the latest backup is retained for the yearly policy.  Surely, at least for the first year, it should be the oldest one?

**Comment by lloyda** [comment]
Still an issue.  Commenting so no longer stale

**Comment by lavinir** [comment]
Yearly is a calendar year. It always attempts to save the latest one. once you cross the year boundary from 2024 to 2025 it will retain the latest one from 2024
