### ISSUE TITLE
Manually trigger file sync possible?

### ISSUE THREAD

**Issue by ministryofsillywalks** [lavinir/hassio-onedrive-backup#219]
First of all thanks a ton for this addon! It works really well.

I have frigate nvr running on my machine and want to store exported clips on my onedrive automatically when I'm not home. (In case someone steals my server that would mean all the recordings of the breakin go missing too...)

So my idea was to save flagged recordings to a media folder and upload to onedrive.
File sync works great but the sync window is every 5 minutes I think?
This would theoretically leave a burglar 5 minutes in which to break in and cut the energy thus leaving me with nothing. (apart from a notification image sent)

So my question is: 
Is there any way to manually trigger the file sync via service call or is there a way to lower the sync interval to say 1 minute?

**Comment by lavinir** [comment]
Sorry, Missed this completely. 
I understand your use case but I have no plans currently to allow this on a trigger. 

I can maybe add to the settings an option to override the sync interval so you could lower it.
