### ISSUE TITLE
Could not start plugin

### ISSUE THREAD

**Issue by GAFL-Knight** [lavinir/hassio-onedrive-backup#221]
When starting the plugin I get the following message: "**Image ghcr.io/lavinir/aarch64-hassonedrive:2.3.1 does not exist for addon_de91e161_hassio_onedrive_backup**"

Please can you help me. Thank you so much.

Screenshot attached
<img width="992" alt="Captura de pantalla 2024-07-16 a la(s) 20 57 35" src="https://github.com/user-attachments/assets/95a9b337-4322-4f75-a267-30de809b0c41">

**Comment by GAFL-Knight** [comment]
I reloaded the plugin again and it worked. I don't know what could have happened.

**Comment by LagaV** [comment]
Seeing the same problem now multiple times. What do you mean with „reload the plugin“ ?
