### ISSUE TITLE
Unable to add to HACS

### ISSUE THREAD

**Issue by coasttech** [lavinir/hassio-onedrive-backup#236]
The option to select repository is no longer there and will not install as a integration.

**Comment by tecfreakz** [comment]
You can add it manually by putting in the repository link to get a custom add on

<img width="220" alt="image" src="https://github.com/user-attachments/assets/f6cfa96b-38f3-4436-ba17-aaa915f9fa3d">

**Comment by coasttech** [comment]
<img width="375" alt="Screenshot 2024-10-11 at 1 06 30 PM" src="https://github.com/user-attachments/assets/506b050d-5566-4c0a-8959-b03ff1312c24">
These are my only options

**Comment by coasttech** [comment]
this does not get installed with hacs lol
