### ISSUE TITLE
Backup keeps saying "Initializing"

### ISSUE THREAD

**Issue by mps222** [lavinir/hassio-onedrive-backup#237]
Authorization to OneDrive has beed given
But still it is not working and keeps saying "Initializing".

What the issue ?
![Screenshot 2024-10-14 094446](https://github.com/user-attachments/assets/484ffbb3-fd2c-4a7a-b0af-ace93c50b54d)

**Comment by lavinir** [comment]
Please set logs to verbose, restart the addon and share the logs.
