### ISSUE TITLE
Request full back-up support

### ISSUE THREAD

**Issue by JelmerD** [lavinir/hassio-onedrive-backup#238]
It would be really nice if I can set a sepparate interval for full backups. Right now (since I'm messing around a lot) I would like to have a full backup every day. But in the future I'd like one every week (at least until I'm certain everything runs smoothly).

**Comment by lavinir** [comment]
What do you mean? You want different configuration for backups for 2 different schedules ?
I think that's introducing a lot of complexity to the config. You could achieve this by having an automation trigger a full backup once a week and just have the addon watch all backups.
