### ISSUE TITLE
1.21 - Sync Interval Hours does not exist in scheme showing HA Supervisor Logs Every Minute

### ISSUE THREAD

**Issue by ziptbm** [lavinir/hassio-onedrive-backup#24]
After upgrading to 1.21, I've noticed this warning persistently every minute in the Supervisor Logs indicating sync_internal_hours does not exist, but the config clearly shows 3.  And this was not changed from what was set before upgrade.

`22-12-02 23:38:52 WARNING (MainThread) [supervisor.addons.options] Option 'sync_interval_hours' does not exist in the schema for OneDrive Backup (de91e161_hassio_onedrive_backup)`

**Comment by lavinir** [comment]
Hm, that setting was removed in the last update. I guess it doesn't remove existing settings from your config. 
You could try clearing the value see if the warning goes away, otherwise removing and re-installing the add-on should probably resolve this.

**Comment by lavinir** [comment]
I checked this locally with other add-ons seeing the same behavior. 
You can just edit the config yaml and remove any deprecated settings and that should resolve it.
