### ISSUE TITLE
Not able to start the Add-on

### ISSUE THREAD

**Issue by Tom-ahawk** [lavinir/hassio-onedrive-backup#242]
Getting this error message when pressing the start button:

"Failed to start add-on
Image ghcr.io/lavinir/aarch64-hassonedrive:2.3.1 does not exist for addon_de91e161_hassio_onedrive_backup"

From the log, looks likes  my latest back up is from "10/12/2024 08:54:32 [68] Info: Upload completed successfully"

Add-on Current version: 2.3.1

Nonetheless, thank you for making this add-on!

Cheers.

**Comment by stefanstranger** [comment]
I'm getting the same error message.

**Comment by stefanstranger** [comment]
Well now it works again. Very strange. I've restarted the onedrive backup add-on after I've downloaded the image via docker pull and now it starts without the error.

Very strange...

**Comment by Tom-ahawk** [comment]
It also works now at my end. Looks like one of the HA core updates was the culprit and the latest HA core fixed the problem
.

**Comment by stefanstranger** [comment]
Right that could also resolved the issue because I also updated to the latest HA core version minutes ago.
