### ISSUE TITLE
Backup to onedrive business

### ISSUE THREAD

**Issue by Landvogt1893** [lavinir/hassio-onedrive-backup#252]
Hey, how can i upload the backups to onedrive business?

**Comment by galgabor24** [comment]
It's in the description: Personal Account only. OneDrive for business not currently supported (see on the screenshot)

![image](https://github.com/user-attachments/assets/9215128e-a6bd-471c-88cd-28771c9daa34)

**Comment by lavinir** [comment]
Right, unfortunately the reasons for this just keep increasing. Related to some of the changes in 2.3.5 as well I had to make in the Entra app for the addon.
