### ISSUE TITLE
URGENT: Endless back-ups

### ISSUE THREAD

**Issue by UweGrunewald** [lavinir/hassio-onedrive-backup#275]
Since a few days, the tool creates backups endlessly every few minutes. The Progress bar starts and starts and starts. How can I avoid this?

![image](https://github.com/user-attachments/assets/5ff00897-2386-4e3b-9380-f24b7fc21e10)

**Comment by UweGrunewald** [comment]
I deleted the One Drive Folder, stopped and started the add-on. No change, issue persist. May the following log lines help to fix the issue?

12/15/2024 07:06:48 [19] Info: Fetching Local Backup (Slug:1e2afdf0)
12/15/2024 07:06:48 [24] Info: Backup (1e2afdf0) fetched successfully
12/15/2024 07:06:49 [31] Info: Starting file upload. (Size:442296320 bytes. Attempt: 1/3)
12/15/2024 07:08:46 [32] Info: Upload completed successfully
12/15/2024 07:08:46 **[29] Warning: Unrecognized file found in backup folder** : 2024-12-14 01_00_00.tar
12/15/2024 07:08:46 [29] Warning: Unrecognized file found in backup folder : 2024-12-15 01_00_00.tar
12/15/2024 07:08:47 [29] Warning: Unrecognized file found in backup folder : 2024-12-14 01_00_00.tar
12/15/2024 07:08:47 [29] Warning: Unrecognized file found in backup folder : 2024-12-15 01_00_00.tar
12/15/2024 07:09:49 [31] Warning: Unrecognized file found in backup folder : 2024-12-14 01_00_00.tar
12/15/2024 07:09:49 [31] Warning: Unrecognized file found in backup folder : 2024-12-15 01_00_00.tar
12/15/2024 07:09:49 [32] Info: Found 1 backups to upload.

**Comment by lavinir** [comment]
Hi,

No, I'd need to see 2 cycles for backups from the logs to see what's happening. It would also help setting the logging level to Verbose.

There is a new version though addressing a few issues that might be applicable to you published in the preview channel (version 2.3.8). Please try and install that version and if the problem persists, share the logs.

**Comment by UweGrunewald** [comment]
Thx a lot for responding. Admittedly however, I am not an HA "expert" and have no glue, how to update to 2.3.8.
I may patiently wait for the official release, except you take your valuable time to teach me how to update. Best, Uwe

**Comment by lavinir** [comment]
It's very similar to the installation you had to do for the release channel. You can find the instructions in the [Installation Instructions](https://github.com/lavinir/hassio-onedrive-backup?tab=readme-ov-file#installation-instructions)
