### ISSUE TITLE
No Password Optoin

### ISSUE THREAD

**Issue by Hawkeye0914** [lavinir/hassio-onedrive-backup#34]
![image](https://user-images.githubusercontent.com/5797426/212761460-48dc954c-7762-48a0-bcfc-d6785ff56ede.png)

After installing there was no option to add a password to the backups in the configuration.  I setup up onedrive and there is still no option.  It backed up fine but was of course not password protected.  I manually added in the password option in the .yaml and created a password but the backup was again not password protected.  After adding the password manually, I did a backup again but it was still not password protected.  The option showed in the configuration panel after editing the .yaml, but  after deleting the password in the configuration panel and restarting the addon, the option is again gone.

Am I the only one without an option to password protect the backups?

**Comment by lavinir** [comment]
This has been changed to an optional option now. You need to toggle the "Show unused optional configuration options" (bottom of your screenshot). It will be visible to you then.
