### ISSUE TITLE
Attributes in HA - missing international date format

### ISSUE THREAD

**Issue by artystazst** [lavinir/hassio-onedrive-backup#38]
Hello
First, I say Thanks for great add-on!

Can I ask to adjust attributes dates to use international date format? Currently, they are in "weird" US format...

Example
`Last Local backup date: 01/18/2023 23:47:07 
Last OneDrive backup date: 01/18/2023 23:47:07`

International date format is YYYY-MM-DD

**Comment by lavinir** [comment]
Out now in v1.41
