### ISSUE TITLE
lack of password option

### ISSUE THREAD

**Issue by turbobeest** [lavinir/hassio-onedrive-backup#47]
There does not appear to be  a password entry in the configuration menu. Please advise. 
![configuration](https://user-images.githubusercontent.com/117555601/218274782-ac445fe8-ca3c-4954-958b-2e4891149159.jpg)

**Comment by lavinir** [comment]
It is now optional to set a password. You can view it in the UI by toggling the "Show unused optional settings" in the addon configuration screen.
