### ISSUE TITLE
Sync Problems

### ISSUE THREAD

**Issue by Jibbonator** [lavinir/hassio-onedrive-backup#54]
Hello,
I Love the Idea of this addon. 
The backup part works flawless and is very useful, thanks for that.

Unfortunately i have 3 Filesync Problems.

I have "Remove deleted files during File Sync" active

1. I cant sync one specific folder:

- path: /addons/paperless_ng/media/documents/originals
   recursive: true

the addon uploads all data and then delets all with with following message:

02/23/2023 22:12:45 [5] Info: /addons is not included in Sync Paths. Deleting from OneDrive
02/23/2023 22:12:45 [5] Info: Deleting item: FileSync/addons

3. If I add more than 1 location, all other than the first are not recognized.

4. The Sync of my folder stops/freezes, if there is a file with 0Kb size.

Can somebody help me?

**Comment by lavinir** [comment]
Could you please share your config and relevant logs for (1) and (4).

**Comment by Jibbonator** [comment]
1:
config:
recovery_mode: false
local_backup_num_to_keep: 7
onedrive_backup_num_to_keep: 7
backup_interval_days: 2
backup_name: hass_backup
monitor_all_local_backups: true
hass_api_timeout_minutes: 30
notify_on_error: true
exclude_media_folder: true
exclude_ssl_folder: false
exclude_share_folder: false
exclude_local_addons_folder: true
sync_paths:
  - path: /media/paperless_ng/media/documents/originals
    recursive: true
file_sync_remove_deleted: true
backup_instance_name: Hass-Jibbo

Logs:
02/25/2023 00:46:37 [13] Info: File /media/paperless_ng/media/documents/originals/xxx/xxx/xxx.pdf out of sync. Starting Upload
02/25/2023 00:46:37 [13] Info: Starting file upload. (Size:29831 bytes. Attempt: 1/3)
02/25/2023 00:46:39 [14] Info: Upload completed successfully
02/25/2023 00:46:39 [14] Info: /media is not included in Sync Paths. Deleting from OneDrive
02/25/2023 00:46:39 [14] Info: Deleting item: FileSync/media



4.
config:
recovery_mode: false
local_backup_num_to_keep: 7
onedrive_backup_num_to_keep: 7
backup_interval_days: 2
backup_name: hass_backup
monitor_all_local_backups: true
hass_api_timeout_minutes: 30
notify_on_error: true
exclude_media_folder: true
exclude_ssl_folder: false
exclude_share_folder: false
exclude_local_addons_folder: true
sync_paths:
  - path: /media/paperless_ng/media
    recursive: true
file_sync_remove_deleted: true
backup_instance_name: Hass-Jibbo


logs:
02/25/2023 00:49:06 [9] Info: Backup interval configured to every 48 hours
02/25/2023 00:49:06 [5] Info: File /media/paperless_ng/media/media.lock out of sync. Starting Upload
02/25/2023 00:49:06 [9] Info: Checking backups
02/25/2023 00:49:07 [5] Info: Retrieving existing local backups...
02/25/2023 00:49:07 [5] Info: Retrieving existing online backups...
02/25/2023 00:49:07 [5] Info: Starting file upload. (Size:0 bytes. Attempt: 1/3)
02/25/2023 00:49:07 [5] Info: Last local backup Date: 02/23/2023 21:36:53
02/25/2023 00:49:07 [5] Info: Last online backup Date: 02/23/2023 21:36:53
02/25/2023 00:49:07 [5] Info: Found 1 backups to upload.
02/25/2023 00:49:07 [11] Info: Uploading 23. Februar 2023 (02/23/2023 09:45:50)
02/25/2023 00:49:07 [11] Info: Fetching Local Backup (Slug:904505ee)
02/25/2023 00:49:07 [7] Info: Backup (904505ee) fetched successfully
02/25/2023 00:49:07 [7] Info: Starting file upload. (Size:10240 bytes. Attempt: 1/3)
02/25/2023 00:49:10 [7] Info: Upload completed successfully
02/25/2023 00:49:10 [7] Info: Backup Interval Completed.
02/25/2023 00:49:17 [10] Error: Error Syncing: System.Threading.Tasks.TaskCanceledException: Upload failed too many times. See InnerException for list of exceptions that occured.
 ---> System.AggregateException: One or more errors occurred.
   --- End of inner exception stack trace ---
   at Microsoft.Graph.LargeFileUploadTask`1.UploadAsync(IProgress`1 progress, Int32 maxTries)
   at hassio_onedrive_backup.Graph.GraphHelper.UploadFileAsync(String filePath, DateTime date, String instanceName, String destinationFileName, Action`1 progressCallback, Boolean flatten, Boolean omitDescription) in /src/Graph/GraphHelper.cs:line 166
   at hassio_onedrive_backup.Sync.SyncManager.SyncFile(String path) in /src/Sync/SyncManager.cs:line 108
   at hassio_onedrive_backup.Sync.SyncManager.SyncDirectory(String path, String filter, Boolean recursive) in /src/Sync/SyncManager.cs:line 144
   at hassio_onedrive_backup.Sync.SyncManager.SyncLoop(CancellationToken ct) in /src/Sync/SyncManager.cs:line 54





Is this enough?

**Comment by lavinir** [comment]
Thank you @Jibbonator . 
The 0kb file seems an issue with the OneDrive API, I will try to work around it or otherwise skip such files (is there a good use case for uploading an empty file?)

For the rest I believe your logs are enough for now, I will add this as part of the work for the next version.

**Comment by Jibbonator** [comment]
The 0Kb files are unfortunately in the Folder i want to sync.
They´re not neccessary for me. 
Is it possible to skip 0kb files or exclude file extensions?

I would have synced just *.pdf files. But than i have the other Problem with the Folder beeing deleted.

Thanks for your work.

**Comment by lavinir** [comment]
The issue with the folder being deleted shouldn't happen and I will look into it.
I will skip 0KB files as well but using a *.pdf mask should also work just fine.

**Comment by Jibbonator** [comment]
OK Thx,
I will wait till the next release to sync my folder.

**Comment by lavinir** [comment]
Version 2.0 is released.
