### ISSUE TITLE
Can't access web UI due to 503 error

### ISSUE THREAD

**Issue by MasterDevwi** [lavinir/hassio-onedrive-backup#59]
I just updated to v2.0 and I'm very excited about the new web UI. I went to the OneDrive Backup info page under add-ons and enabled the "Show in sidebar" setting, but when I click on OneDrive Backup in the sidebar (or select "Open web UI" on the info page) I get a 503: Service Unavailable error.

I've tried restarting Home Assistant, but the issue still repros.

**Comment by MasterDevwi** [comment]
For whatever reason, it finally started working. I wonder if there's a brief delay before the web UI is accessible?

**Comment by robertboccia** [comment]
Having same issue but mine still not displaying after restart

**Comment by lavinir** [comment]
I had the same thing actually happen to me - seems to be some caching the happens when upgrading from the previous version. 
Try to update the configuration and have the addon restart, that cleared it for me.

Worst case - if you uninstall and reinstall I imagine this will resolve the issue.

**Comment by arobsco** [comment]
Same issue here will give it some time before trying a reinstall. No errors in logs of anything

**Comment by hockey6611** [comment]
Same issue for me. Was fixed by [clearing cache and a hard reload](https://help.codehs.com/en/articles/4951972-how-to-clear-your-browser-cache-and-hard-refresh#h_dfff8ab987) in chrome.
