### ISSUE TITLE
Exclude folders & set time for backup

### ISSUE THREAD

**Issue by antonio1475** [lavinir/hassio-onedrive-backup#6]
Hi,

Thank you for the add-on. As my Google storage runs low, I appreciate using my empty OneDrive instead...
I hope adding an Enhancement request here is fine (I see a label for it), so that it's visible for all.

Coming from the Google Drive Add-on, I inmediately miss the ability to exclude folders. Apart from optimizing the space, also the time & resources dedicated to a backup. My partial backups were 1/6th 😅 
![image](https://user-images.githubusercontent.com/63130724/198901513-2ef5493d-74c9-4ac0-ae66-a5962d1dd4c8.png)

Which of course causes https://github.com/lavinir/hassio-onedrive-backup/issues/4 and although that will be fixed, it can be attacked at the source by excluding useless folders :)

Related to this, but to avoid creating another issue for now: ability to set the time to do the backup (eg. 6AM).

Thank you! 😄

**Comment by lavinir** [comment]
Partial folder backup is now available in V1.1. 
I added a specific time of day schedule to the backlog.
