### ISSUE TITLE
File Sync not working?

### ISSUE THREAD

**Issue by Seba200086** [lavinir/hassio-onedrive-backup#67]
Hi,

First and foremost - an excellent tool! This is something I have sorely missed!

I have a small problem with folder synchronisation. 
To limit the size of the backup and speed up the build process, I moved the database (homeassistant.db) to the /**media**/hass_db/homeassistant.db directory.

I excluded folder media (exclude_media_folder: true) and set its synchronisation:
```
sync_paths:
  - /media/ (I also tried - /media and - /media/**/* and - /media/*...).
file_sync_remove_deleted: false
```

From the web page, I selected "Trigger backup". A new backup was created, but the media directory was not synchronised (no new FileSync directory was created in the [onedriveroot]/Apps/hassio-onedrive-backup directory).

Am I doing something wrong?

**Comment by lavinir** [comment]
Hi, thanks.

the 'Trigger Backup' button only triggers a backup :) 
The File Syncing occurs in the background , you cannot manually trigger a sync but this occurs every 5 minutes. 

your sync_paths definition  of "/media/" looks fine. Could you restart the addon and share the logs - It should indicate when it finds a new file that is out of sync and attempt to upload it.

**Comment by lavinir** [comment]
right ok - so you have the "allowed hours" option set to 2 meaning backups and syncs will only occur between 2:00 and 2:59.
That's why you aren't seeing any syncing.

**Comment by Seba200086** [comment]
Ahh. OK. I'm so stupid 🤦‍♂️
```
03/23/2023 16:21:14 [6] Info: Backup interval configured to every 72 hours
03/23/2023 16:21:14 [6] Info: Backups / Syncs will only run during these hours: 2,14,15,16,17,18
03/23/2023 16:21:19 [6] Info: Checking backups
03/23/2023 16:21:19 [6] Info: Backup Interval Completed.
03/23/2023 16:21:20 [6] Info: Retrieving existing local backups...
03/23/2023 16:21:20 [6] Info: Retrieving existing online backups...
03/23/2023 16:21:20 [6] Info: Last local backup Date: 03/22/2023 21:34:23
03/23/2023 16:21:20 [6] Info: Last online backup Date: 03/22/2023 21:34:23
03/23/2023 16:21:20 [6] Info: Online backups synced. No upload required
03/23/2023 16:21:44 [10] Info: File /media/hass_db/home-assistant_v2.db out of sync. Starting Upload
03/23/2023 16:21:45 [10] Info: Starting file upload. (Size:1048240128 bytes. Attempt: 1/3)
```
Seems to be ok now!
Thank you!

**Comment by lavinir** [comment]
by the way, are you sure you want the db file uploaded each time it changes ? there is no differential sync going on here as OneDrive do not expose that API externally meaning the entire file would be uploaded each time there is a change.
@Seba200086

**Comment by Seba200086** [comment]
Good question. I probably haven't thought it through.
I will save some space in backups (each copy is 750 MB without database vs 1050 MB with database) but (in my case) 1 GB of data extra every 3 days to transfer (that's how much my database takes up).
I have 1TB of space available in OneDrive, so I think I'll actually go back to what it was before....
Syncing folders makes sense for photos, videos, etc.
Thank you!
