### ISSUE TITLE
Bad time in log

### ISSUE THREAD

**Issue by leroyloren** [lavinir/hassio-onedrive-backup#7]
Hi,

i see in the changlog for 1.1 that the time was fixed, but not yet. It is shifted by -1 hour compared to the state in HA.

![obrazek](https://user-images.githubusercontent.com/57643470/199028299-9364aa3a-c947-4a91-9170-a821058e933f.png)

![obrazek](https://user-images.githubusercontent.com/57643470/199028349-17106006-fc6b-4710-b618-73ee84583b90.png)

**Comment by lavinir** [comment]
Nothing was 'fixed' or changed with regards to the timezone in 1.1. 
The time shown should be UTC time, are you seeing something else ?

**Comment by leroyloren** [comment]
Yes, the time is UTC.

I am now in Central European Time (CET), UTC +1 and, the time in HA is correct.

**Comment by lavinir** [comment]
So is there an issue or not ? :)

**Comment by leroyloren** [comment]
The time in the add-on log is an hour less compared to the current time and the time in HA

**Comment by lavinir** [comment]
I understand. I'm showing the time in UTC , Home Assistant displays Local Time. I'll change this in the next update.

**Comment by bandi72** [comment]
By the way, you can ask to change the date format to European :-) The copy is saved in the 2022-11-28 format and it's OK here, but the dashboard is 28/11/2022

**Comment by lavinir** [comment]
Fixed in 1.2
