### ISSUE TITLE
Feature request: Set daily time of backup

### ISSUE THREAD

**Issue by user45876** [lavinir/hassio-onedrive-backup#8]
It would be nice to set the time, when backups occur. For instance, I (sometime last week) set the addon up at 16:30 and now backups are occuring daily at 16:30 forever. Backups should, however, be done during the deep night.

I now put in a sync interval of 32 hours, to have the check shifted further (only once, will put it back to 1 hour afterwards).

It would be great, if there was an option to set the daily time of backup.

Thanks for your great work!

**Comment by lavinir** [comment]
1.2 is out and should address this issue. 
See [here](https://github.com/lavinir/hassio-onedrive-backup#backup_allowed_hours-optional)

**Comment by user45876** [comment]
Thank you very much :)
