### ISSUE TITLE
Failed creating local backup

### ISSUE THREAD

**Issue by bjk201** [lavinir/hassio-onedrive-backup#85]
Hello,

everyday i get a error Message in the Notification Center. 

„ Failed creating local backup. Check Addon logs for more details“

My Settings:

2 times a Day Backup. The Last 4 locally and 25 online. 

Log:

05/03/2023 21:10:19 [57] Info: Backup complete
05/03/2023 21:15:20 [58] Info: Creating new backup
05/03/2023 21:15:20 [58] Info: Starting full local backup
05/03/2023 21:15:20 [22] Info: Backup complete
05/03/2023 21:20:21 [30] Info: Creating new backup
05/03/2023 21:20:21 [30] Info: Starting full local backup
05/03/2023 21:20:21 [30] Info: Backup complete
05/03/2023 21:25:22 [24] Info: Creating new backup
05/03/2023 21:25:22 [24] Info: Starting full local backup
05/03/2023 21:25:22 [24] Info: Backup complete
05/03/2023 21:30:23 [57] Info: Creating new backup
05/03/2023 21:30:23 [57] Info: Starting full local backup
05/03/2023 21:30:23 [57] Info: Backup complete
05/03/2023 21:35:25 [31] Info: Creating new backup
05/03/2023 21:35:25 [31] Info: Starting full local backup
05/03/2023 21:35:25 [31] Info: Backup complete
05/03/2023 21:40:26 [19] Info: Creating new backup
05/03/2023 21:40:26 [19] Info: Starting full local backup
05/03/2023 21:40:26 [19] Info: Backup complete
05/03/2023 21:45:37 [18] Info: Creating new backup
05/03/2023 21:45:37 [18] Info: Starting full local backup
05/03/2023 21:45:37 [18] Info: Backup complete
05/03/2023 21:50:38 [24] Info: Found 1 backups to upload.
05/03/2023 21:50:38 [24] Info: Uploading hass_backup_2023-05-03-19-40 (05/03/2023 19:40:03)
05/03/2023 21:50:38 [24] Info: Fetching Local Backup (Slug:c6f16063)
05/03/2023 21:54:35 [29] Info: Backup (c6f16063) fetched successfully
05/03/2023 21:54:41 [29] Info: Starting file upload. (Size:12586117120 bytes. Attempt: 1/3)
05/04/2023 00:33:21 [54] Info: Upload completed successfully
05/04/2023 00:33:25 [68] Info: Found 1 backups to delete from OneDrive.
05/04/2023 00:33:25 [68] Info: Deleting item: hass_backup_2023-04-20-03-18.tar
05/04/2023 00:33:25 [68] Info: Removing 1 local backups
05/04/2023 07:42:21 [50] Info: Creating new backup
05/04/2023 07:42:21 [50] Info: Starting full local backup
05/04/2023 08:42:21 [32] Error: Backup request timed out. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 3600 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at hassio_onedrive_backup.Hass.HassioClient.CreateBackupAsync(String backupName, Boolean appendTimestamp, Boolean compressed, String password, IEnumerable`1 folders, IEnumerable`1 addons) in /src/Hass/HassioClient.cs:line 129
05/04/2023 08:42:21 [32] Error: Increase the timeout value in configuration
05/04/2023 08:42:33 [69] Info: Creating new backup
05/04/2023 08:42:33 [69] Info: Starting full local backup
05/04/2023 08:42:33 [69] Info: Backup complete
05/04/2023 08:47:34 [69] Info: Creating new backup
05/04/2023 08:47:34 [69] Info: Starting full local backup
05/04/2023 08:47:34 [69] Info: Backup complete
05/04/2023 08:52:35 [47] Info: Creating new backup
05/04/2023 08:52:35 [47] Info: Starting full local backup
05/04/2023 08:52:35 [47] Info: Backup complete
05/04/2023 08:57:36 [69] Info: Creating new backup
05/04/2023 08:57:36 [69] Info: Starting full local backup
05/04/2023 08:57:36 [69] Info: Backup complete
05/04/2023 09:02:37 [47] Info: Creating new backup
05/04/2023 09:02:37 [47] Info: Starting full local backup
05/04/2023 09:02:37 [21] Info: Backup complete
05/04/2023 09:07:39 [72] Info: Creating new backup
05/04/2023 09:07:39 [72] Info: Starting full local backup
05/04/2023 09:07:39 [72] Info: Backup complete
05/04/2023 09:12:40 [72] Info: Creating new backup
05/04/2023 09:12:40 [72] Info: Starting full local backup
05/04/2023 09:12:40 [32] Info: Backup complete
05/04/2023 09:17:41 [8] Info: Creating new backup
05/04/2023 09:17:41 [8] Info: Starting full local backup
05/04/2023 09:17:41 [57] Info: Backup complete
05/04/2023 09:22:42 [71] Info: Creating new backup
05/04/2023 09:22:42 [71] Info: Starting full local backup
05/04/2023 09:22:42 [71] Info: Backup complete
05/04/2023 09:27:43 [55] Info: Creating new backup
05/04/2023 09:27:43 [55] Info: Starting full local backup
05/04/2023 09:27:43 [35] Info: Backup complete
05/04/2023 09:32:45 [50] Info: Creating new backup
05/04/2023 09:32:45 [50] Info: Starting full local backup
05/04/2023 09:32:45 [50] Info: Backup complete
05/04/2023 09:37:46 [35] Info: Creating new backup
05/04/2023 09:37:46 [35] Info: Starting full local backup
05/04/2023 09:37:46 [35] Info: Backup complete
05/04/2023 09:42:47 [50] Info: Creating new backup
05/04/2023 09:42:47 [50] Info: Starting full local backup
05/04/2023 09:42:47 [71] Info: Backup complete
05/04/2023 09:47:49 [57] Info: Creating new backup
05/04/2023 09:47:49 [57] Info: Starting full local backup
05/04/2023 09:47:49 [57] Info: Backup complete
05/04/2023 09:52:49 [54] Info: Found 1 backups to upload.
05/04/2023 09:52:49 [54] Info: Uploading hass_backup_2023-05-04-07-42 (05/04/2023 07:42:21)
05/04/2023 09:52:49 [54] Info: Fetching Local Backup (Slug:b79d6e16)
05/04/2023 09:57:00 [38] Info: Backup (b79d6e16) fetched successfully
05/04/2023 09:57:07 [46] Info: Starting file upload. (Size:12581181440 bytes. Attempt: 1/3)

**Comment by lavinir** [comment]
see [here](https://github.com/lavinir/hassio-onedrive-backup#im-getting-an-error-failed-creating-new-backup-message)
