### ISSUE TITLE
Docker container doesn't start

### ISSUE THREAD

**Issue by Liam-Whiteside** [lavinir/hassio-onedrive-backup#86]
I'm running HA on Ubuntu 22.04 using docker. I've installed several other addons successfully, however when I try to install the onedrive backup add on it installs, I can click "start" but when I then try to go to the UI it says "Add-onn is not running. Please start it first"

In system log it shows this:
May 15 22:51:03 server kernel: [123242.008009] audit: type=1400 audit(1684187463.186:76): apparmor="DENIED" operation="create" class="net" profile="de91e161_hassio_onedrive_backup" pid=292057 comm=2E4E455420546872656164506F6F6C family="inet6" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create"
May 15 22:51:03 server kernel: [123242.008014] audit: type=1400 audit(1684187463.186:77): apparmor="DENIED" operation="create" class="net" profile="de91e161_hassio_onedrive_backup" pid=292057 comm=2E4E455420546872656164506F6F6C family="inet" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create"
May 15 22:51:03 server kernel: [123242.010307] audit: type=1400 audit(1684187463.186:78): apparmor="DENIED" operation="create" class="net" profile="de91e161_hassio_onedrive_backup" pid=292057 comm=2E4E455420546872656164506F6F6C family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"

**Comment by lavinir** [comment]
These are conflicting permissions with the apparmor profile defined for the addon. This doesn't present any issues though when running on HassOS or Supervised to my knowledge. 
You are running with Supervisor right ?

**Comment by Liam-Whiteside** [comment]
This is what I'm running, technically it's an unsupported setup as the OS is too new:

Version | core-2023.5.3
Installation Type | Home Assistant Supervised
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.11
Operating System Family | Linux
Operating System Version | 5.19.0-41-generic
CPU Architecture | x86_64
Timezone | Europe/London
Configuration Directory | /config

Home Assistant Supervisor
Host Operating System | Ubuntu 22.04.2 LTS
Update Channel | stable
Supervisor Version | supervisor-2023.04.1
Agent Version | 1.5.1
Docker Version | 23.0.6
Disk Total | 233.2 GB
Disk Used | 80.5 GB
Healthy | true
Supported | Unsupported
Supervisor API | ok
Version API | ok

**Comment by Liam-Whiteside** [comment]
Adding this to the apparmor file for the add-on does allow it to work, but I don't know enough about the architecture to know if this is the correct solution
  network,
  deny network raw,

**Comment by lavinir** [comment]
I'm not sure either. If this was applicable to all supervised installations it might shed more light on why the profile is failing but I'm not aware of issues with other Supervised installations.

You're saying updating the apparmor file resolved this for you ?

**Comment by Liam-Whiteside** [comment]
Yes, updating that apparmor file with those two lines fixed it for me.
I'm running another 10 add-ons and don't have any other apparmor files in /usr/share/hassio/apparmor other than the hassio-supervisor one and the one I edited for onedrive backup

**Comment by churchofnoise** [comment]
This also solves my issue #84

**Comment by ingrove** [comment]
This also solves my issue #2

**Comment by lavinir** [comment]
Great! I will make modifications to the packaged apparmor file to accomodate the needed permissiosn for supervised installs.

**Comment by lavinir** [comment]
This should now be resolved in 2.1.2
