### ISSUE TITLE
Code for authentication reported as 'expired' - how to get new code

### ISSUE THREAD

**Issue by jph1ll1ps** [lavinir/hassio-onedrive-backup#87]
after logging into https://microsoft.com/devicelogin  - authenticated etc, the system reports the Code used is expired... how to refresh the code and get a new one?

**Comment by lavinir** [comment]
Restarting the add-on should restart the auth flow and give a new code.

**Comment by jph1ll1ps** [comment]
resterted... but had to clean up files first... the sdcard was full haha.
