### ISSUE TITLE
home assistant to crash

### ISSUE THREAD

**Issue by wolfhond** [lavinir/hassio-onedrive-backup#92]
The add-on causes my home assistant to crash. I have the latest version of both. Only when I disable the add-on does my home assistant work normally. I think it's since the last update of the add-on but I'm not sure.

**Comment by markusg1234** [comment]
How are you disabling the add-on? 
I can't now get the add-on store to load and a number of the main side bar options is missing.

**Comment by lavinir** [comment]
I'm confused. 
@wolfhond  - Addons just run inside containers, not sure how this would cause Home Assistant to crash. What exactly are you seeing in the logs? How are you running Home Assistant ?
@markusg1234  - Is your comment related to the same issue ? Are you also having a problem with the addon ?

**Comment by markusg1234** [comment]
Hi, Yes. 
Running HA OS. HA 2023.6.0.b1  Supervisor 2023.06.0
After starting the addon it would show only the online storage percentage and wouldn't finish updating the screen.
I left it for about 20min and then restarted HA. After restarting HA the Addons page just shows a spinning circle. 
Also the main HA sidebar is missing everything after Media. I think after media was the Onedrive tab.
I am now unable to uninstall Onedrive via the Gui or SSH. 

ha addon uninstall de91e161_hassio_onedrive_backup      Comes back as FATA[0000] Error while executing rootCmd: accepts 1 arg(s), received 0 arg(s

  return self.data[ATTR_NAME]
           ^^^^^^^^^
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 226, in data
    return self.sys_addons.data.system[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'de91e161_hassio_onedrive_backup'
23-06-04 09:21:44 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
23-06-04 09:21:44 ERROR (MainThread) [aiohttp.server] Error handling request

If I try to restore HA it hangs in the GUI and SSH comes back with

 ha backups restore bcf79c5a
Processing... Done.

Error: Unknown error, see supervisor



File "/usr/src/supervisor/supervisor/addons/addon.py", line 226, in data
    return self.sys_addons.data.system[self.slug]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'de91e161_hassio_onedrive_backup'

**Comment by markusg1234** [comment]
Was able to get HA working again by doing the following.
ha core update 
ha su repair
rebooting ha

message displayed unsupported operating system. Looks like ha didn't like the onedrive_backup container. 

Reinstalled Addon via GUI as GUI was now working.
Uninstalled Addon.
Reboot Ha.
All fixed minus onedrive_backup.

Now running Running HA OS. HA 2023.6.0.b4 Supervisor 2023.06.0

**Comment by lavinir** [comment]
That's very odd.  So you are now running without the addon installed? 
Seems would be more likely a HA issue if installing the add-on would have this effect.

Any chance you'd try re-installing it and see what happens ?

**Comment by hvdb** [comment]
Hello,

So I have the same issue with supervised installation.
It 'randomly' crashed, right after when this addon had created a backup.
After setting allowed hours differently, to make sure nothing else is running.

I can confirm that it crashes the system.
But why...

In the logging i see that it's uploading, it comes to 70% and then it crashes.

So some logging;

syslog:
`Jul  1 07:08:15 homeassistant addon_de91e161_hassio_onedrive_backup[639]: 07/01/2023 07:08:15 [57] Verbose: Uploaded 70%
Jul  1 07:08:30 homeassistant kernel: [ 3778.406250] ------------[ cut here ]------------
Jul  1 07:08:30 homeassistant kernel: [ 3778.406348] NETDEV WATCHDOG: enx00e04c3612fa (r8152): transmit queue 0 timed out
Jul  1 07:08:30 homeassistant kernel: [ 3778.406444] WARNING: CPU: 1 PID: 0 at net/sched/sch_generic.c:467 dev_watchdog+0x260/0x270
Jul  1 07:08:30 homeassistant kernel: [ 3778.406456] Modules linked in: rfcomm xt_nat xt_tcpudp veth xt_conntrack nft_chain_nat xt_MASQUERADE nf_nat nf_conntrack_netlink nf_conntrack nf_defrag_ipv6 nf_defrag_ipv4 xfrm_user xfrm_algo nft_counter xt_addrtype nft_compat nf_tables libcrc32c nfnetlink br_netfilter bridge stp llc cmac algif_hash algif_skcipher af_alg bnep overlay snd_hdmi_lpe_audio hid_asus snd_soc_sst_bytcr_rt5640 intel_rapl_msr gpio_keys mei_hdcp intel_soc_dts_thermal intel_powerclamp coretemp kvm_intel brcmfmac kvm hci_uart brcmutil nls_ascii nls_cp437 irqbypass vfat fat btqca btrtl ghash_clmulni_intel btbcm cfg80211 asus_nb_wmi evdev btintel efi_pstore intel_cstate asus_wmi joydev pcspkr sparse_keymap bluetooth hid_multitouch cdc_ether jitterentropy_rng ak8975 usbnet r8152 mii sd_mod iTCO_wdt ftdi_sio drbg t10_pi usbhid crc_t10dif intel_pmc_bxt crct10dif_generic usbserial iTCO_vendor_support sg i915 watchdog snd_soc_rt5670 button snd_soc_rt5651 aes_generic snd_soc_rt5645 snd_intel_sst_acpi soc_button_array
Jul  1 07:08:30 homeassistant kernel: [ 3778.407200]  snd_intel_sst_core processor_thermal_device int3406_thermal intel_rapl_common int3400_thermal snd_soc_sst_atom_hifi2_platform int3403_thermal intel_soc_dts_iosf aesni_intel int340x_thermal_zone acpi_thermal_rel snd_soc_acpi_intel_match snd_soc_rt5640 snd_soc_acpi crypto_simd snd_soc_rl6231 cryptd glue_helper snd_soc_core asus_wireless intel_int0002_vgpio drm_kms_helper acpi_pad ansi_cprng snd_compress ac ecdh_generic mei_txe snd_pcm inv_mpu6050_i2c cec inv_mpu6050 snd_timer pwm_lpss_platform industrialio_triggered_buffer mei i2c_algo_bit rfkill kfifo_buf cm32181 snd pwm_lpss ecc i2c_mux industrialio libaes soundcore drm fuse configfs efivarfs ip_tables x_tables autofs4 ext4 crc16 mbcache jbd2 crc32c_generic uas usb_storage scsi_mod xhci_pci xhci_hcd hid_generic crct10dif_pclmul crct10dif_common mmc_block usbcore crc32_pclmul crc32c_intel i2c_hid lpc_ich usb_common wmi video sdhci_acpi sdhci dw_dmac dw_dmac_core hid mmc_core battery
Jul  1 07:08:30 homeassistant kernel: [ 3778.407890] CPU: 1 PID: 0 Comm: swapper/1 Not tainted 5.10.0-23-amd64 #1 Debian 5.10.179-1
Jul  1 07:08:30 homeassistant kernel: [ 3778.407901] Hardware name: ASUSTeK COMPUTER INC. T100TA/T100TA, BIOS T100TA.304 03/14/2014
Jul  1 07:08:30 homeassistant kernel: [ 3778.407920] RIP: 0010:dev_watchdog+0x260/0x270
Jul  1 07:08:30 homeassistant kernel: [ 3778.407939] Code: eb a9 48 8b 1c 24 c6 05 88 95 0c 01 01 48 89 df e8 55 72 fa ff 44 89 e9 48 89 de 48 c7 c7 30 c2 76 a4 48 89 c2 e8 95 ae 14 00 <0f> 0b eb 86 66 66 2e 0f 1f 84 00 00 00 00 00 90 0f 1f 44 00 00 41`

In userlog

I do see around the same time an error which has to do with another add-on.

As I did a system reboot dockers logs are gone..
Next time I will see if i can still login (ssh doesn't work) and check docker logs.


But maybe you some some clue :)
Think it has something todo with a process executed after the backup is created, either by this add-on or supervisor.

**Comment by markusg1234** [comment]
I remember that when I had the issue, HA was also doing a backup using google drive backup at the time.

**Comment by lavinir** [comment]
Have you had an older version of the addon working ? There was a change that was supposed to resolve an issue with having a Supervised installation that had to do with the app armor file.  
My guess is the answer is somewhere in those settings.

**Comment by markusg1234** [comment]
> Have you had an older version of the addon working ? There was a change that was supposed to resolve an issue with having a Supervised installation that had to do with the app armor file. My guess is the answer is somewhere in those settings.

No, I have only ever tried the latest version and it had the issue.
Regards,
Markus

**Comment by hvdb** [comment]
> Have you had an older version of the addon working ? There was a change that was supposed to resolve an issue with having a Supervised installation that had to do with the app armor file.
> My guess is the answer is somewhere in those settings.

I have it running for 2months now and had no issues previously.
Not sure when I updated tho.

But indeed that can be a possible cause of the problem

**Comment by lavinir** [comment]
Are you able to make changes to the app armor file ? You could revert it to before the change and see if that works.

**Comment by hvdb** [comment]
Sorry was away :)
Hum, let me have a look on how to do that

**Comment by garyjohnwalker** [comment]
I think I'm experiencing the same issue.
Installed yesterday, came to check to see if it had backed up tonight and HA was restarting.
I eventually managed to get into add-ons and was able to stop it.

Anything useful I can grab and post here to help diagnose this?

**Comment by lavinir** [comment]
Are you also not running HassOS ? Can you access the apparmor file ?

**Comment by garyjohnwalker** [comment]
Unfortunately I am on HassOS but if this apparmor file is accessable via HassOS, I have gained access in the past using the documented (but not supported) method. If you can provide details of what is needed, I can give it a try.

**Comment by lavinir** [comment]
You are running HassOS ? This seems exteremly odd. The addon just runs as a container and should not have any negative effect on HA.  Could you please describe exactly what you're experiencing and if you can find any logs (addon / supervisor) that may help here?
Also what architecture are you running on ?

**Comment by garyjohnwalker** [comment]
It's a Pi4 8Gb (excessive but you take what you can find now days).
It appears to be just the Supervisor that crashes.
Not got access at the moment but I'll grab logs when I can

**Comment by garyjohnwalker** [comment]
OK, so I can't give you logs as it looks like one of the supervisor restarts/crashes has corrupted my supervisor. I'm currently erasing and restoring from backup. When I'm back up, I'll decide whether I turn the add-on back on.

**Comment by lavinir** [comment]
Ok, if this is somehow causing issues with supervisor it seems like it's an issue that should be opened for Home Assistant regardless, the add-on should not be able to cause something like this.

**Comment by garyjohnwalker** [comment]
Time for an update.
I'm now less convinced my corruption was directly caused by this. It's probably more a case that it was the straw that broke the camel's back.

After serveral restores and further issues (with this add-on stopped), I've concluded the root cause of my issues was power. I have the official Pi4 PS (15.3W, 3A) that claims to be "all the power your [Raspberry Pi 4 Model B] will need" but it turns out it isn't. I'm now on a laptop USB-C 90W power supply and things seem to have settled down.

I've tried the add-on again once and this time had no issues. The increase in CPU and disk activity when this runs will mean more power use and I suspect this was enough to max out the PS before causing the erratic behavour.

If it helps, I have my Pi4 in an Argon One M.2 case. The SSD in these cases is powered via USB 3.0 which means additional power use.
I also have a skylink for Zigbee and  a Coral for Frigate all of which will use power.

I'm not willing to say at this point that there isn't an issue but it's worth everyone that is having issues checking for power problems. I have the Raspberry Pi Power Supply Checker integration installed and assuming the power doesn'y drop sufficiently to cause a crash, this will highlight blips. You can even set up a notification when it triggers. It's a slighter cruder method but hooking up a monitor and watching for the lightning symbol also works.

I'm interested to know if other people see the same.

**Comment by lavinir** [comment]
Yeah while I think the addon should not be able to do something like this I'm not ruling out that some configuration or other might be triggering an issue though it's kind of hard to diagnose here.

Thanks for sharing this, please update if you have additional info to share.

**Comment by Pronown** [comment]
I'm experiencing this as well. If I uninstall the addon before it loads, I'm good. If this addon starts though, it immediately murders supervisor on HASSOS. It stops any of the Supervisor related processes, backups, add-ons etc. I would love to be able to use this but can confirm it's something with the add-on vs HASSOS.

**Comment by Pronown** [comment]
Just wondering if there's been any update to this or if I can help in some way?

**Comment by lavinir** [comment]
@sudoxnym , @bariz74 

Sorry for the late response. Unfortunately I don't have much too much insights here. Because the Add-ons run isolated in containers, they shouldn't be causing this in Home Assistant. Even if the addon has an issue and crashes it should still not cause Home Assistant to stop loading. 

My suggestion is to try and open an issue with Home Assistant, I'm happy to weigh in or add relevant information on the addon if needed.
