### ISSUE TITLE
Authentication code not working

### ISSUE THREAD

**Issue by Dimgoossens** [lavinir/hassio-onedrive-backup#93]
Hi,
Since a couple of days backups are failing.
When I open the addon i get a message to use a code to authenticate and the devices url.
When I enter the code it says invalid.
Can I generate a new code, or is there something else wrong?

**Comment by lavinir** [comment]
A new code should be generated if you restart the add-on. Could you please try that and confirm the code in the logs, then try to authenticate again ?

**Comment by Dimgoossens** [comment]
> A new code should be generated if you restart the add-on. Could you please try that and confirm the code in the logs, then try to authenticate again ?

Thanks!!! This does the trick!! It seems to expire after a while, and restarting it indeed does create a new one!
