### ISSUE TITLE
File Sync Paths don't seem to work

### ISSUE THREAD

**Issue by gsbgit** [lavinir/hassio-onedrive-backup#99]
Hi,
I tried to backup my Node Red flows, packages and settings, but I don't see any of the files shown up at my One Drive.
The normal backup seems to work (the tar file is created and uploaded to One Drive), but no FileSync folder is created.
I tried it also with a folder Filesync I created myself.
Tried File Sync Paths with and without leading  slash.

My File Sync Paths:

/config/node-red/flows.json
/config/node-red/package.json
/config/node-red/settings.js

Is there something else I could try or I'm doing wrong?

Thanks in advance

**Comment by lavinir** [comment]
Not much I do without seeing the logs.  Make sure you follow the instructions [here](https://github.com/lavinir/hassio-onedrive-backup#file-sync-paths-optional)
If you still experience issues please post the logs

**Comment by lavinir** [comment]
@gsbgit  - 2.2 was released. If you're still experiencing issues feel free to open a new issue and add your logs.
